public class ActionLinkGroupTemplate {
    public ActionLinkTemplate[] actionLinkTemplates;
    public String category;
    public String executionsAllowed;
    public Integer hoursUntilExpiration;
    public Boolean isPublished;
    public String name;
    private String[] actionLinkTemplates_type_info = new String[]{'actionLinkTemplates','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] category_type_info = new String[]{'category','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] executionsAllowed_type_info = new String[]{'executionsAllowed','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] hoursUntilExpiration_type_info = new String[]{'hoursUntilExpiration','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isPublished_type_info = new String[]{'isPublished','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionLinkTemplates','category','executionsAllowed','hoursUntilExpiration','isPublished','name'};
}