public class ActionLinkTemplate {
    public String actionUrl;
    public String headers;
    public Boolean isConfirmationRequired;
    public Boolean isGroupDefault;
    public String label;
    public String labelKey;
    public String linkType;
    public String method;
    public Integer position;
    public String requestBody;
    public String userAlias;
    public String userVisibility;
    private String[] actionUrl_type_info = new String[]{'actionUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] headers_type_info = new String[]{'headers','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isConfirmationRequired_type_info = new String[]{'isConfirmationRequired','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isGroupDefault_type_info = new String[]{'isGroupDefault','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] labelKey_type_info = new String[]{'labelKey','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] linkType_type_info = new String[]{'linkType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] method_type_info = new String[]{'method','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] position_type_info = new String[]{'position','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] requestBody_type_info = new String[]{'requestBody','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] userAlias_type_info = new String[]{'userAlias','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] userVisibility_type_info = new String[]{'userVisibility','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionUrl','headers','isConfirmationRequired','isGroupDefault','label','labelKey','linkType','method','position','requestBody','userAlias','userVisibility'};
}