public class CustomHttpHeader {
    public String description;
    public String headerFieldName;
    public String headerFieldValue;
    public Boolean isActive;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] headerFieldName_type_info = new String[]{'headerFieldName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] headerFieldValue_type_info = new String[]{'headerFieldValue','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isActive_type_info = new String[]{'isActive','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','headerFieldName','headerFieldValue','isActive'};
}