public class IpRange {
    public String description;
    public String end_x;
    public String start;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] end_x_type_info = new String[]{'end','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] start_type_info = new String[]{'start','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','end_x','start'};
}