public class PasswordPolicies {
    public String apiOnlyUserHomePageURL;
    public String complexity;
    public String expiration;
    public String historyRestriction;
    public String lockoutInterval;
    public String maxLoginAttempts;
    public String minimumPasswordLength;
    public Boolean minimumPasswordLifetime;
    public Boolean obscureSecretAnswer;
    public String passwordAssistanceMessage;
    public String passwordAssistanceURL;
    public String questionRestriction;
    private String[] apiOnlyUserHomePageURL_type_info = new String[]{'apiOnlyUserHomePageURL','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] complexity_type_info = new String[]{'complexity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] expiration_type_info = new String[]{'expiration','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] historyRestriction_type_info = new String[]{'historyRestriction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lockoutInterval_type_info = new String[]{'lockoutInterval','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] maxLoginAttempts_type_info = new String[]{'maxLoginAttempts','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] minimumPasswordLength_type_info = new String[]{'minimumPasswordLength','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] minimumPasswordLifetime_type_info = new String[]{'minimumPasswordLifetime','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] obscureSecretAnswer_type_info = new String[]{'obscureSecretAnswer','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] passwordAssistanceMessage_type_info = new String[]{'passwordAssistanceMessage','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] passwordAssistanceURL_type_info = new String[]{'passwordAssistanceURL','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] questionRestriction_type_info = new String[]{'questionRestriction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apiOnlyUserHomePageURL','complexity','expiration','historyRestriction','lockoutInterval','maxLoginAttempts','minimumPasswordLength','minimumPasswordLifetime','obscureSecretAnswer','passwordAssistanceMessage','passwordAssistanceURL','questionRestriction'};
}