public class SecuritySettings {
    public Boolean canUsersGrantLoginAccess;
    public Boolean enableAdminLoginAsAnyUser;
    public Boolean enableAuditFieldsInactiveOwner;
    public Boolean enableAuraSecureEvalPref;
    public Boolean enableRequireHttpsConnection;
    public NetworkAccess networkAccess;
    public PasswordPolicies passwordPolicies;
    public SessionSettings sessionSettings;
    public SingleSignOnSettings singleSignOnSettings;
    private String[] canUsersGrantLoginAccess_type_info = new String[]{'canUsersGrantLoginAccess','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAdminLoginAsAnyUser_type_info = new String[]{'enableAdminLoginAsAnyUser','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAuditFieldsInactiveOwner_type_info = new String[]{'enableAuditFieldsInactiveOwner','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAuraSecureEvalPref_type_info = new String[]{'enableAuraSecureEvalPref','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableRequireHttpsConnection_type_info = new String[]{'enableRequireHttpsConnection','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] networkAccess_type_info = new String[]{'networkAccess','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] passwordPolicies_type_info = new String[]{'passwordPolicies','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sessionSettings_type_info = new String[]{'sessionSettings','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] singleSignOnSettings_type_info = new String[]{'singleSignOnSettings','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'canUsersGrantLoginAccess','enableAdminLoginAsAnyUser','enableAuditFieldsInactiveOwner','enableAuraSecureEvalPref','enableRequireHttpsConnection','networkAccess','passwordPolicies','sessionSettings','singleSignOnSettings'};
}