public class SingleSignOnSettings {
    public Boolean enableCaseInsensitiveFederationID;
    public Boolean enableForceDelegatedCallout;
    public Boolean enableMultipleSamlConfigs;
    public Boolean enableSamlJitProvisioning;
    public Boolean enableSamlLogin;
    public Boolean isLoginWithSalesforceCredentialsDisabled;
    private String[] enableCaseInsensitiveFederationID_type_info = new String[]{'enableCaseInsensitiveFederationID','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableForceDelegatedCallout_type_info = new String[]{'enableForceDelegatedCallout','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMultipleSamlConfigs_type_info = new String[]{'enableMultipleSamlConfigs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSamlJitProvisioning_type_info = new String[]{'enableSamlJitProvisioning','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSamlLogin_type_info = new String[]{'enableSamlLogin','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isLoginWithSalesforceCredentialsDisabled_type_info = new String[]{'isLoginWithSalesforceCredentialsDisabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCaseInsensitiveFederationID','enableForceDelegatedCallout','enableMultipleSamlConfigs','enableSamlJitProvisioning','enableSamlLogin','isLoginWithSalesforceCredentialsDisabled'};
}