public class ApprovalSubmitter {
    public String submitter;
    public String type_x;
    private String[] submitter_type_info = new String[]{'submitter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'submitter','type_x'};
}