public class EntitlementProcessMilestoneItem {
    public String businessHours;
    public String criteriaBooleanFilter;
    public FilterItem[] milestoneCriteriaFilterItems;
    public String milestoneCriteriaFormula;
    public String milestoneName;
    public String minutesCustomClass;
    public Integer minutesToComplete;
    public WorkflowActionReference[] successActions;
    public EntitlementProcessMilestoneTimeTrigger[] timeTriggers;
    public Boolean useCriteriaStartTime;
    private String[] businessHours_type_info = new String[]{'businessHours','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] criteriaBooleanFilter_type_info = new String[]{'criteriaBooleanFilter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] milestoneCriteriaFilterItems_type_info = new String[]{'milestoneCriteriaFilterItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] milestoneCriteriaFormula_type_info = new String[]{'milestoneCriteriaFormula','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] milestoneName_type_info = new String[]{'milestoneName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] minutesCustomClass_type_info = new String[]{'minutesCustomClass','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] minutesToComplete_type_info = new String[]{'minutesToComplete','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] successActions_type_info = new String[]{'successActions','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] timeTriggers_type_info = new String[]{'timeTriggers','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] useCriteriaStartTime_type_info = new String[]{'useCriteriaStartTime','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'businessHours','criteriaBooleanFilter','milestoneCriteriaFilterItems','milestoneCriteriaFormula','milestoneName','minutesCustomClass','minutesToComplete','successActions','timeTriggers','useCriteriaStartTime'};
}