public class NextAutomatedApprover {
    public Boolean useApproverFieldOfRecordOwner;
    public String userHierarchyField;
    private String[] useApproverFieldOfRecordOwner_type_info = new String[]{'useApproverFieldOfRecordOwner','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] userHierarchyField_type_info = new String[]{'userHierarchyField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'useApproverFieldOfRecordOwner','userHierarchyField'};
}