public class WorkflowFieldUpdate {
    public String description;
    public String field;
    public String formula;
    public String literalValue;
    public String lookupValue;
    public String lookupValueType;
    public String name;
    public Boolean notifyAssignee;
    public String operation;
    public Boolean protected_x;
    public Boolean reevaluateOnChange;
    public String targetObject;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] formula_type_info = new String[]{'formula','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] literalValue_type_info = new String[]{'literalValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lookupValue_type_info = new String[]{'lookupValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lookupValueType_type_info = new String[]{'lookupValueType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] notifyAssignee_type_info = new String[]{'notifyAssignee','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] operation_type_info = new String[]{'operation','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] protected_x_type_info = new String[]{'protected','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] reevaluateOnChange_type_info = new String[]{'reevaluateOnChange','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] targetObject_type_info = new String[]{'targetObject','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','field','formula','literalValue','lookupValue','lookupValueType','name','notifyAssignee','operation','protected_x','reevaluateOnChange','targetObject'};
}