public class WorkflowOutboundMessage {
    public Double apiVersion;
    public String description;
    public String endpointUrl;
    public String[] fields;
    public Boolean includeSessionId;
    public String integrationUser;
    public String name;
    public Boolean protected_x;
    public Boolean useDeadLetterQueue;
    private String[] apiVersion_type_info = new String[]{'apiVersion','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] endpointUrl_type_info = new String[]{'endpointUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] fields_type_info = new String[]{'fields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] includeSessionId_type_info = new String[]{'includeSessionId','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] integrationUser_type_info = new String[]{'integrationUser','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] protected_x_type_info = new String[]{'protected','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] useDeadLetterQueue_type_info = new String[]{'useDeadLetterQueue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apiVersion','description','endpointUrl','fields','includeSessionId','integrationUser','name','protected_x','useDeadLetterQueue'};
}