public class WorkflowTask {
    public String assignedTo;
    public String assignedToType;
    public String description;
    public Integer dueDateOffset;
    public Boolean notifyAssignee;
    public String offsetFromField;
    public String priority;
    public Boolean protected_x;
    public String status;
    public String subject;
    private String[] assignedTo_type_info = new String[]{'assignedTo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] assignedToType_type_info = new String[]{'assignedToType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dueDateOffset_type_info = new String[]{'dueDateOffset','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] notifyAssignee_type_info = new String[]{'notifyAssignee','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] offsetFromField_type_info = new String[]{'offsetFromField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] priority_type_info = new String[]{'priority','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] protected_x_type_info = new String[]{'protected','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] status_type_info = new String[]{'status','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] subject_type_info = new String[]{'subject','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignedTo','assignedToType','description','dueDateOffset','notifyAssignee','offsetFromField','priority','protected_x','status','subject'};
}