public class ProfileActionOverride {
    public String actionName;
    public String content;
    public String formFactor;
    public String pageOrSobjectType;
    public String recordType;
    public String type_x;
    private String[] actionName_type_info = new String[]{'actionName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] content_type_info = new String[]{'content','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] formFactor_type_info = new String[]{'formFactor','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] pageOrSobjectType_type_info = new String[]{'pageOrSobjectType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] recordType_type_info = new String[]{'recordType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionName','content','formFactor','pageOrSobjectType','recordType','type_x'};
}