public class ProfilePasswordPolicy {
    public Boolean forgotPasswordRedirect;
    public Integer lockoutInterval;
    public Integer maxLoginAttempts;
    public Integer minimumPasswordLength;
    public Boolean minimumPasswordLifetime;
    public Boolean obscure;
    public Integer passwordComplexity;
    public Integer passwordExpiration;
    public Integer passwordHistory;
    public Integer passwordQuestion;
    public String profile;
    private String[] forgotPasswordRedirect_type_info = new String[]{'forgotPasswordRedirect','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lockoutInterval_type_info = new String[]{'lockoutInterval','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] maxLoginAttempts_type_info = new String[]{'maxLoginAttempts','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] minimumPasswordLength_type_info = new String[]{'minimumPasswordLength','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] minimumPasswordLifetime_type_info = new String[]{'minimumPasswordLifetime','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] obscure_type_info = new String[]{'obscure','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] passwordComplexity_type_info = new String[]{'passwordComplexity','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] passwordExpiration_type_info = new String[]{'passwordExpiration','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] passwordHistory_type_info = new String[]{'passwordHistory','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] passwordQuestion_type_info = new String[]{'passwordQuestion','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] profile_type_info = new String[]{'profile','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'forgotPasswordRedirect','lockoutInterval','maxLoginAttempts','minimumPasswordLength','minimumPasswordLifetime','obscure','passwordComplexity','passwordExpiration','passwordHistory','passwordQuestion','profile'};
}