public class ProfileSessionSetting {
    public Boolean externalCommunityUserIdentityVerif;
    public Boolean forceLogout;
    public String profile;
    public String requiredSessionLevel;
    public Boolean sessionPersistence;
    public Integer sessionTimeout;
    public Boolean sessionTimeoutWarning;
    private String[] externalCommunityUserIdentityVerif_type_info = new String[]{'externalCommunityUserIdentityVerif','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] forceLogout_type_info = new String[]{'forceLogout','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] profile_type_info = new String[]{'profile','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] requiredSessionLevel_type_info = new String[]{'requiredSessionLevel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sessionPersistence_type_info = new String[]{'sessionPersistence','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sessionTimeout_type_info = new String[]{'sessionTimeout','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sessionTimeoutWarning_type_info = new String[]{'sessionTimeoutWarning','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'externalCommunityUserIdentityVerif','forceLogout','profile','requiredSessionLevel','sessionPersistence','sessionTimeout','sessionTimeoutWarning'};
}