public class ProfileCategoryGroupVisibility {
    public String[] dataCategories;
    public String dataCategoryGroup;
    public String visibility;
    private String[] dataCategories_type_info = new String[]{'dataCategories','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] dataCategoryGroup_type_info = new String[]{'dataCategoryGroup','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] visibility_type_info = new String[]{'visibility','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dataCategories','dataCategoryGroup','visibility'};
}