public class ChartSummary {
    public String aggregate;
    public String axisBinding;
    public String column;
    private String[] aggregate_type_info = new String[]{'aggregate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] axisBinding_type_info = new String[]{'axisBinding','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] column_type_info = new String[]{'column','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregate','axisBinding','column'};
}