public class DashboardComponentColumn {
    public Double breakPoint1;
    public Double breakPoint2;
    public Integer breakPointOrder;
    public Integer highRangeColor;
    public Integer lowRangeColor;
    public Integer midRangeColor;
    public String reportColumn;
    public Boolean showSubTotal;
    public Boolean showTotal;
    public String type_x;
    private String[] breakPoint1_type_info = new String[]{'breakPoint1','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] breakPoint2_type_info = new String[]{'breakPoint2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] breakPointOrder_type_info = new String[]{'breakPointOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] highRangeColor_type_info = new String[]{'highRangeColor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lowRangeColor_type_info = new String[]{'lowRangeColor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] midRangeColor_type_info = new String[]{'midRangeColor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] reportColumn_type_info = new String[]{'reportColumn','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] showSubTotal_type_info = new String[]{'showSubTotal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showTotal_type_info = new String[]{'showTotal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'breakPoint1','breakPoint2','breakPointOrder','highRangeColor','lowRangeColor','midRangeColor','reportColumn','showSubTotal','showTotal','type_x'};
}