public class DashboardGridComponent {
    public Integer colSpan;
    public Integer columnIndex;
    public DashboardComponent dashboardComponent;
    public Integer rowIndex;
    public Integer rowSpan;
    private String[] colSpan_type_info = new String[]{'colSpan','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] columnIndex_type_info = new String[]{'columnIndex','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] dashboardComponent_type_info = new String[]{'dashboardComponent','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] rowIndex_type_info = new String[]{'rowIndex','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] rowSpan_type_info = new String[]{'rowSpan','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'colSpan','columnIndex','dashboardComponent','rowIndex','rowSpan'};
}