public class DashboardFlexTableComponentProperties {
    public Integer decimalPrecision;
    public DashboardComponentColumn[] flexTableColumn;
    public DashboardComponentSortInfo flexTableSortInfo;
    public Boolean hideChatterPhotos;
    private String[] decimalPrecision_type_info = new String[]{'decimalPrecision','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] flexTableColumn_type_info = new String[]{'flexTableColumn','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] flexTableSortInfo_type_info = new String[]{'flexTableSortInfo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] hideChatterPhotos_type_info = new String[]{'hideChatterPhotos','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'decimalPrecision','flexTableColumn','flexTableSortInfo','hideChatterPhotos'};
}