public class DashboardGridLayout {
    public DashboardGridComponent[] dashboardGridComponents;
    public Integer numberOfColumns;
    public Integer rowHeight;
    private String[] dashboardGridComponents_type_info = new String[]{'dashboardGridComponents','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] numberOfColumns_type_info = new String[]{'numberOfColumns','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] rowHeight_type_info = new String[]{'rowHeight','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dashboardGridComponents','numberOfColumns','rowHeight'};
}