public class DashboardComponentGroupingSort {
    public String groupingLevel;
    public String inheritedReportGroupingSort;
    public String sortColumn;
    public String sortOrder;
    private String[] groupingLevel_type_info = new String[]{'groupingLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] inheritedReportGroupingSort_type_info = new String[]{'inheritedReportGroupingSort','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortColumn_type_info = new String[]{'sortColumn','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortOrder_type_info = new String[]{'sortOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'groupingLevel','inheritedReportGroupingSort','sortColumn','sortOrder'};
}