public class DashboardTableColumn {
    public String aggregateType;
    public Boolean calculatePercent;
    public String column;
    public Integer decimalPlaces;
    public Boolean showSubTotal;
    public Boolean showTotal;
    public String sortBy;
    private String[] aggregateType_type_info = new String[]{'aggregateType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] calculatePercent_type_info = new String[]{'calculatePercent','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] column_type_info = new String[]{'column','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] decimalPlaces_type_info = new String[]{'decimalPlaces','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showSubTotal_type_info = new String[]{'showSubTotal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showTotal_type_info = new String[]{'showTotal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortBy_type_info = new String[]{'sortBy','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregateType','calculatePercent','column','decimalPlaces','showSubTotal','showTotal','sortBy'};
}