public class ReportBucketFieldSourceValue {
    public String from_x;
    public String sourceValue;
    public String to;
    private String[] from_x_type_info = new String[]{'from','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sourceValue_type_info = new String[]{'sourceValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] to_type_info = new String[]{'to','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'from_x','sourceValue','to'};
}