public class ReportBucketFieldValue {
    public ReportBucketFieldSourceValue[] sourceValues;
    public String value;
    private String[] sourceValues_type_info = new String[]{'sourceValues','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] value_type_info = new String[]{'value','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'sourceValues','value'};
}