public class ReportGrouping {
    public String aggregateType;
    public String dateGranularity;
    public String field;
    public String sortByName;
    public String sortOrder;
    public String sortType;
    private String[] aggregateType_type_info = new String[]{'aggregateType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dateGranularity_type_info = new String[]{'dateGranularity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sortByName_type_info = new String[]{'sortByName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortOrder_type_info = new String[]{'sortOrder','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sortType_type_info = new String[]{'sortType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregateType','dateGranularity','field','sortByName','sortOrder','sortType'};
}