public class ReportBucketField {
    public String bucketType;
    public String developerName;
    public String masterLabel;
    public String nullTreatment;
    public String otherBucketLabel;
    public String sourceColumnName;
    public Boolean useOther;
    public ReportBucketFieldValue[] values;
    private String[] bucketType_type_info = new String[]{'bucketType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] nullTreatment_type_info = new String[]{'nullTreatment','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] otherBucketLabel_type_info = new String[]{'otherBucketLabel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sourceColumnName_type_info = new String[]{'sourceColumnName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] useOther_type_info = new String[]{'useOther','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] values_type_info = new String[]{'values','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'bucketType','developerName','masterLabel','nullTreatment','otherBucketLabel','sourceColumnName','useOther','values'};
}