public class ReportColumn {
    public String[] aggregateTypes;
    public String field;
    public Boolean reverseColors;
    public Boolean showChanges;
    private String[] aggregateTypes_type_info = new String[]{'aggregateTypes','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] reverseColors_type_info = new String[]{'reverseColors','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showChanges_type_info = new String[]{'showChanges','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregateTypes','field','reverseColors','showChanges'};
}