public class ReportColorRange {
    public String aggregate;
    public String columnName;
    public Double highBreakpoint;
    public String highColor;
    public Double lowBreakpoint;
    public String lowColor;
    public String midColor;
    private String[] aggregate_type_info = new String[]{'aggregate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] columnName_type_info = new String[]{'columnName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] highBreakpoint_type_info = new String[]{'highBreakpoint','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] highColor_type_info = new String[]{'highColor','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] lowBreakpoint_type_info = new String[]{'lowBreakpoint','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lowColor_type_info = new String[]{'lowColor','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] midColor_type_info = new String[]{'midColor','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregate','columnName','highBreakpoint','highColor','lowBreakpoint','lowColor','midColor'};
}