public class ReportTypeColumn {
    public Boolean checkedByDefault;
    public String displayNameOverride;
    public String field;
    public String table;
    private String[] checkedByDefault_type_info = new String[]{'checkedByDefault','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] displayNameOverride_type_info = new String[]{'displayNameOverride','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] table_type_info = new String[]{'table','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'checkedByDefault','displayNameOverride','field','table'};
}