public class ReportCustomDetailFormula {
    public String calculatedFormula;
    public String dataType;
    public String description;
    public String developerName;
    public String label;
    public Integer scale;
    private String[] calculatedFormula_type_info = new String[]{'calculatedFormula','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] dataType_type_info = new String[]{'dataType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] scale_type_info = new String[]{'scale','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'calculatedFormula','dataType','description','developerName','label','scale'};
}