public class ReportBlockInfo {
    public ReportAggregateReference[] aggregateReferences;
    public String blockId;
    public String joinTable;
    private String[] aggregateReferences_type_info = new String[]{'aggregateReferences','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] blockId_type_info = new String[]{'blockId','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] joinTable_type_info = new String[]{'joinTable','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aggregateReferences','blockId','joinTable'};
}