public class ReportAggregate {
    public String acrossGroupingContext;
    public String calculatedFormula;
    public String datatype;
    public String description;
    public String developerName;
    public String downGroupingContext;
    public Boolean isActive;
    public Boolean isCrossBlock;
    public String masterLabel;
    public String reportType;
    public Integer scale;
    private String[] acrossGroupingContext_type_info = new String[]{'acrossGroupingContext','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] calculatedFormula_type_info = new String[]{'calculatedFormula','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] datatype_type_info = new String[]{'datatype','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] downGroupingContext_type_info = new String[]{'downGroupingContext','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isActive_type_info = new String[]{'isActive','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isCrossBlock_type_info = new String[]{'isCrossBlock','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] reportType_type_info = new String[]{'reportType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] scale_type_info = new String[]{'scale','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'acrossGroupingContext','calculatedFormula','datatype','description','developerName','downGroupingContext','isActive','isCrossBlock','masterLabel','reportType','scale'};
}