public class BusinessProcessFeedback {
    public String actionName;
    public String actionParam;
    public String actionType;
    private String[] actionName_type_info = new String[]{'actionName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] actionParam_type_info = new String[]{'actionParam','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] actionType_type_info = new String[]{'actionType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionName','actionParam','actionType'};
}