public class Group_x {
    public Boolean doesIncludeBosses;
    public String name;
    private String[] doesIncludeBosses_type_info = new String[]{'doesIncludeBosses','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'doesIncludeBosses','name'};
}