public class QueueMembers {
    public PublicGroups publicGroups;
    public RoleAndSubordinates roleAndSubordinates;
    public RoleAndSubordinatesInternal roleAndSubordinatesInternal;
    public Roles roles;
    public Users users;
    private String[] publicGroups_type_info = new String[]{'publicGroups','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] roleAndSubordinates_type_info = new String[]{'roleAndSubordinates','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] roleAndSubordinatesInternal_type_info = new String[]{'roleAndSubordinatesInternal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] roles_type_info = new String[]{'roles','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] users_type_info = new String[]{'users','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'publicGroups','roleAndSubordinates','roleAndSubordinatesInternal','roles','users'};
}