public class RoleOrTerritory {
    public String caseAccessLevel;
    public String contactAccessLevel;
    public String description;
    public Boolean mayForecastManagerShare;
    public String name;
    public String opportunityAccessLevel;
    private String[] caseAccessLevel_type_info = new String[]{'caseAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] contactAccessLevel_type_info = new String[]{'contactAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] mayForecastManagerShare_type_info = new String[]{'mayForecastManagerShare','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] opportunityAccessLevel_type_info = new String[]{'opportunityAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'caseAccessLevel','contactAccessLevel','description','mayForecastManagerShare','name','opportunityAccessLevel'};
}