public class UserProvisioningConfig {
    public String approvalRequired;
    public String connectedApp;
    public Boolean enabled;
    public String enabledOperations;
    public String flow;
    public String masterLabel;
    public String namedCredential;
    public String notes;
    public String onUpdateAttributes;
    public String reconFilter;
    public String userAccountMapping;
    private String[] approvalRequired_type_info = new String[]{'approvalRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] connectedApp_type_info = new String[]{'connectedApp','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enabled_type_info = new String[]{'enabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enabledOperations_type_info = new String[]{'enabledOperations','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] flow_type_info = new String[]{'flow','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] namedCredential_type_info = new String[]{'namedCredential','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] notes_type_info = new String[]{'notes','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] onUpdateAttributes_type_info = new String[]{'onUpdateAttributes','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] reconFilter_type_info = new String[]{'reconFilter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] userAccountMapping_type_info = new String[]{'userAccountMapping','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'approvalRequired','connectedApp','enabled','enabledOperations','flow','masterLabel','namedCredential','notes','onUpdateAttributes','reconFilter','userAccountMapping'};
}