public class CampaignInfluenceModel {
    public Boolean isActive;
    public Boolean isDefaultModel;
    public Boolean isModelLocked;
    public String modelDescription;
    public String name;
    public String recordPreference;
    private String[] isActive_type_info = new String[]{'isActive','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isDefaultModel_type_info = new String[]{'isDefaultModel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isModelLocked_type_info = new String[]{'isModelLocked','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] modelDescription_type_info = new String[]{'modelDescription','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] recordPreference_type_info = new String[]{'recordPreference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'isActive','isDefaultModel','isModelLocked','modelDescription','name','recordPreference'};
}