public class PaymentGatewayProvider {
    public String apexAdapter;
    public String comments;
    public String idempotencySupported;
    public String masterLabel;
    private String[] apexAdapter_type_info = new String[]{'apexAdapter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] comments_type_info = new String[]{'comments','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idempotencySupported_type_info = new String[]{'idempotencySupported','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apexAdapter','comments','idempotencySupported','masterLabel'};
}