public class BatchDataSrcFilterCriteria {
    public Boolean dynamicValue;
    public String dynamicValueType;
    public String fieldName;
    public String fieldValue;
    public String operator;
    public Integer sequenceNo;
    private String[] dynamicValue_type_info = new String[]{'dynamicValue','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] dynamicValueType_type_info = new String[]{'dynamicValueType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] fieldName_type_info = new String[]{'fieldName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] fieldValue_type_info = new String[]{'fieldValue','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] operator_type_info = new String[]{'operator','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sequenceNo_type_info = new String[]{'sequenceNo','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dynamicValue','dynamicValueType','fieldName','fieldValue','operator','sequenceNo'};
}