public class ChannelLayout {
    public Boolean doesExcludeFieldLabels;
    public Boolean doesExcludeFiles;
    public String[] enabledChannels;
    public String label;
    public ChannelLayoutItem[] layoutItems;
    public String recordType;
    private String[] doesExcludeFieldLabels_type_info = new String[]{'doesExcludeFieldLabels','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesExcludeFiles_type_info = new String[]{'doesExcludeFiles','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enabledChannels_type_info = new String[]{'enabledChannels','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] layoutItems_type_info = new String[]{'layoutItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] recordType_type_info = new String[]{'recordType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'doesExcludeFieldLabels','doesExcludeFiles','enabledChannels','label','layoutItems','recordType'};
}