public class CanvasMetadata {
    public String accessMethod;
    public String canvasOptions;
    public String canvasUrl;
    public String lifecycleClass;
    public String locationOptions;
    public String samlInitiationMethod;
    private String[] accessMethod_type_info = new String[]{'accessMethod','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] canvasOptions_type_info = new String[]{'canvasOptions','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] canvasUrl_type_info = new String[]{'canvasUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] lifecycleClass_type_info = new String[]{'lifecycleClass','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] locationOptions_type_info = new String[]{'locationOptions','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlInitiationMethod_type_info = new String[]{'samlInitiationMethod','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'accessMethod','canvasOptions','canvasUrl','lifecycleClass','locationOptions','samlInitiationMethod'};
}