public class ConnectedAppOauthConfig {
    public ConnectedAppOauthAssetToken assetTokenConfig;
    public String callbackUrl;
    public String certificate;
    public String consumerKey;
    public String consumerSecret;
    public ConnectedAppOauthIdToken idTokenConfig;
    public Boolean isAdminApproved;
    public Boolean isConsumerSecretOptional;
    public Boolean isIntrospectAllTokens;
    public Boolean isSecretRequiredForRefreshToken;
    public String[] scopes;
    public String singleLogoutUrl;
    private String[] assetTokenConfig_type_info = new String[]{'assetTokenConfig','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] callbackUrl_type_info = new String[]{'callbackUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] certificate_type_info = new String[]{'certificate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] consumerKey_type_info = new String[]{'consumerKey','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] consumerSecret_type_info = new String[]{'consumerSecret','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idTokenConfig_type_info = new String[]{'idTokenConfig','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isAdminApproved_type_info = new String[]{'isAdminApproved','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isConsumerSecretOptional_type_info = new String[]{'isConsumerSecretOptional','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isIntrospectAllTokens_type_info = new String[]{'isIntrospectAllTokens','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isSecretRequiredForRefreshToken_type_info = new String[]{'isSecretRequiredForRefreshToken','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] scopes_type_info = new String[]{'scopes','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] singleLogoutUrl_type_info = new String[]{'singleLogoutUrl','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assetTokenConfig','callbackUrl','certificate','consumerKey','consumerSecret','idTokenConfig','isAdminApproved','isConsumerSecretOptional','isIntrospectAllTokens','isSecretRequiredForRefreshToken','scopes','singleLogoutUrl'};
}