public class ConnectedAppAttribute {
    public String formula;
    public String key;
    private String[] formula_type_info = new String[]{'formula','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] key_type_info = new String[]{'key','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'formula','key'};
}