public class ConnectedAppSamlConfig {
    public String acsUrl;
    public String certificate;
    public String encryptionCertificate;
    public String encryptionType;
    public String entityUrl;
    public String issuer;
    public String samlIdpSLOBindingEnum;
    public String samlNameIdFormat;
    public String samlSigningAlgoType;
    public String samlSloUrl;
    public String samlSubjectCustomAttr;
    public String samlSubjectType;
    private String[] acsUrl_type_info = new String[]{'acsUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] certificate_type_info = new String[]{'certificate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] encryptionCertificate_type_info = new String[]{'encryptionCertificate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] encryptionType_type_info = new String[]{'encryptionType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] entityUrl_type_info = new String[]{'entityUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] issuer_type_info = new String[]{'issuer','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlIdpSLOBindingEnum_type_info = new String[]{'samlIdpSLOBindingEnum','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlNameIdFormat_type_info = new String[]{'samlNameIdFormat','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlSigningAlgoType_type_info = new String[]{'samlSigningAlgoType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlSloUrl_type_info = new String[]{'samlSloUrl','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlSubjectCustomAttr_type_info = new String[]{'samlSubjectCustomAttr','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] samlSubjectType_type_info = new String[]{'samlSubjectType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'acsUrl','certificate','encryptionCertificate','encryptionType','entityUrl','issuer','samlIdpSLOBindingEnum','samlNameIdFormat','samlSigningAlgoType','samlSloUrl','samlSubjectCustomAttr','samlSubjectType'};
}