public class ConnectedAppOauthPolicy {
    public String ipRelaxation;
    public String refreshTokenPolicy;
    public String singleLogoutUrl;
    private String[] ipRelaxation_type_info = new String[]{'ipRelaxation','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] refreshTokenPolicy_type_info = new String[]{'refreshTokenPolicy','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] singleLogoutUrl_type_info = new String[]{'singleLogoutUrl','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'ipRelaxation','refreshTokenPolicy','singleLogoutUrl'};
}