public class ConnectedAppCanvasConfig {
    public String accessMethod;
    public String canvasUrl;
    public String lifecycleClass;
    public String[] locations;
    public String[] options;
    public String samlInitiationMethod;
    private String[] accessMethod_type_info = new String[]{'accessMethod','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] canvasUrl_type_info = new String[]{'canvasUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] lifecycleClass_type_info = new String[]{'lifecycleClass','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] locations_type_info = new String[]{'locations','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] options_type_info = new String[]{'options','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] samlInitiationMethod_type_info = new String[]{'samlInitiationMethod','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'accessMethod','canvasUrl','lifecycleClass','locations','options','samlInitiationMethod'};
}