public class ConnectedAppOauthIdToken {
    public String idTokenAudience;
    public Boolean idTokenIncludeAttributes;
    public Boolean idTokenIncludeCustomPerms;
    public Boolean idTokenIncludeStandardClaims;
    public Integer idTokenValidity;
    private String[] idTokenAudience_type_info = new String[]{'idTokenAudience','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idTokenIncludeAttributes_type_info = new String[]{'idTokenIncludeAttributes','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idTokenIncludeCustomPerms_type_info = new String[]{'idTokenIncludeCustomPerms','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idTokenIncludeStandardClaims_type_info = new String[]{'idTokenIncludeStandardClaims','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] idTokenValidity_type_info = new String[]{'idTokenValidity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'idTokenAudience','idTokenIncludeAttributes','idTokenIncludeCustomPerms','idTokenIncludeStandardClaims','idTokenValidity'};
}