public class ConnectedAppOauthAssetToken {
    public String assetAudiences;
    public Boolean assetIncludeAttributes;
    public Boolean assetIncludeCustomPerms;
    public String assetSigningCertId;
    public Integer assetValidityPeriod;
    private String[] assetAudiences_type_info = new String[]{'assetAudiences','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] assetIncludeAttributes_type_info = new String[]{'assetIncludeAttributes','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] assetIncludeCustomPerms_type_info = new String[]{'assetIncludeCustomPerms','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] assetSigningCertId_type_info = new String[]{'assetSigningCertId','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] assetValidityPeriod_type_info = new String[]{'assetValidityPeriod','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assetAudiences','assetIncludeAttributes','assetIncludeCustomPerms','assetSigningCertId','assetValidityPeriod'};
}