public class Document {
    public String description;
    public Boolean internalUseOnly;
    public String keywords;
    public String name;
    public Boolean public_x;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] internalUseOnly_type_info = new String[]{'internalUseOnly','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] keywords_type_info = new String[]{'keywords','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] public_x_type_info = new String[]{'public','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','internalUseOnly','keywords','name','public_x'};
}