public class CspTrustedSite {
    public String context;
    public String description;
    public String endpointUrl;
    public Boolean isActive;
    public Boolean isApplicableToConnectSrc;
    public Boolean isApplicableToFontSrc;
    public Boolean isApplicableToFrameSrc;
    public Boolean isApplicableToImgSrc;
    public Boolean isApplicableToMediaSrc;
    public Boolean isApplicableToStyleSrc;
    public String mobileExtension;
    private String[] context_type_info = new String[]{'context','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] endpointUrl_type_info = new String[]{'endpointUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isActive_type_info = new String[]{'isActive','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isApplicableToConnectSrc_type_info = new String[]{'isApplicableToConnectSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isApplicableToFontSrc_type_info = new String[]{'isApplicableToFontSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isApplicableToFrameSrc_type_info = new String[]{'isApplicableToFrameSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isApplicableToImgSrc_type_info = new String[]{'isApplicableToImgSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isApplicableToMediaSrc_type_info = new String[]{'isApplicableToMediaSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isApplicableToStyleSrc_type_info = new String[]{'isApplicableToStyleSrc','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] mobileExtension_type_info = new String[]{'mobileExtension','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'context','description','endpointUrl','isActive','isApplicableToConnectSrc','isApplicableToFontSrc','isApplicableToFrameSrc','isApplicableToImgSrc','isApplicableToMediaSrc','isApplicableToStyleSrc','mobileExtension'};
}