public class InboundCertificate {
    public Date expirationDate;
    public String issuer;
    public String masterLabel;
    public String serialId;
    private String[] expirationDate_type_info = new String[]{'expirationDate','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] issuer_type_info = new String[]{'issuer','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] serialId_type_info = new String[]{'serialId','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'expirationDate','issuer','masterLabel','serialId'};
}