public class IPAddressRange {
    public String description;
    public String endIpAddress;
    public String ipAddressFeature;
    public String ipAddressUsageScope;
    public Boolean isProtected;
    public String masterLabel;
    public String startIpAddress;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] endIpAddress_type_info = new String[]{'endIpAddress','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] ipAddressFeature_type_info = new String[]{'ipAddressFeature','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] ipAddressUsageScope_type_info = new String[]{'ipAddressUsageScope','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isProtected_type_info = new String[]{'isProtected','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] startIpAddress_type_info = new String[]{'startIpAddress','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','endIpAddress','ipAddressFeature','ipAddressUsageScope','isProtected','masterLabel','startIpAddress'};
}