public class MyDomainDiscoverableLogin {
    public String apexHandler;
    public String executeApexHandlerAs;
    public String usernameLabel;
    private String[] apexHandler_type_info = new String[]{'apexHandler','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] executeApexHandlerAs_type_info = new String[]{'executeApexHandlerAs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] usernameLabel_type_info = new String[]{'usernameLabel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apexHandler','executeApexHandlerAs','usernameLabel'};
}