public class OauthCustomScope {
    public OauthCustomScopeApp[] assignedTo;
    public String description;
    public String developerName;
    public Boolean isProtected;
    public Boolean isPublic;
    public String masterLabel;
    private String[] assignedTo_type_info = new String[]{'assignedTo','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isProtected_type_info = new String[]{'isProtected','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isPublic_type_info = new String[]{'isPublic','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignedTo','description','developerName','isProtected','isPublic','masterLabel'};
}