public class UserAuthCertificate {
    public String developerName;
    public DateTime expirationDate;
    public String masterLabel;
    public String serialNumber;
    public String user_x;
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] expirationDate_type_info = new String[]{'expirationDate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] serialNumber_type_info = new String[]{'serialNumber','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] user_x_type_info = new String[]{'user','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'developerName','expirationDate','masterLabel','serialNumber','user_x'};
}