public class ActionPlanTemplateItemDependency {
    public String creationType;
    public String name;
    public ActionPlanTemplateItem previousTemplateItem;
    public ActionPlanTemplateItem templateItem;
    private String[] creationType_type_info = new String[]{'creationType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] previousTemplateItem_type_info = new String[]{'previousTemplateItem','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] templateItem_type_info = new String[]{'templateItem','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'creationType','name','previousTemplateItem','templateItem'};
}