public class ActionPlanTemplateItem {
    public ActionPlanTemplateItemValue[] actionPlanTemplateItemValue;
    public Integer displayOrder;
    public Boolean isRequired;
    public String itemEntityType;
    public String name;
    public String uniqueName;
    private String[] actionPlanTemplateItemValue_type_info = new String[]{'actionPlanTemplateItemValue','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] displayOrder_type_info = new String[]{'displayOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isRequired_type_info = new String[]{'isRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] itemEntityType_type_info = new String[]{'itemEntityType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] uniqueName_type_info = new String[]{'uniqueName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionPlanTemplateItemValue','displayOrder','isRequired','itemEntityType','name','uniqueName'};
}