public class ActionPlanTemplateItemValue {
    public String itemEntityType;
    public String name;
    public String valueFormula;
    public String valueLiteral;
    private String[] itemEntityType_type_info = new String[]{'itemEntityType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] valueFormula_type_info = new String[]{'valueFormula','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] valueLiteral_type_info = new String[]{'valueLiteral','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'itemEntityType','name','valueFormula','valueLiteral'};
}