public class ActionOverride {
    public String actionName;
    public String comment;
    public String content;
    public String formFactor;
    public Boolean skipRecordTypeSelect;
    public String type_x;
    private String[] actionName_type_info = new String[]{'actionName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] comment_type_info = new String[]{'comment','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] content_type_info = new String[]{'content','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] formFactor_type_info = new String[]{'formFactor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] skipRecordTypeSelect_type_info = new String[]{'skipRecordTypeSelect','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'actionName','comment','content','formFactor','skipRecordTypeSelect','type_x'};
}