public class ContentAssetRelationships {
    public ContentAssetLink[] emailTemplate;
    public ContentAssetLink[] insightsApplication;
    public ContentAssetLink[] network;
    public ContentAssetLink organization;
    public ContentAssetLink[] workspace;
    private String[] emailTemplate_type_info = new String[]{'emailTemplate','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] insightsApplication_type_info = new String[]{'insightsApplication','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] network_type_info = new String[]{'network','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] organization_type_info = new String[]{'organization','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] workspace_type_info = new String[]{'workspace','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'emailTemplate','insightsApplication','network','organization','workspace'};
}