public class ContentAsset {
    public String format;
    public Boolean isVisibleByExternalUsers;
    public String language;
    public String masterLabel;
    public String originNetwork;
    public ContentAssetRelationships relationships;
    public ContentAssetVersions versions;
    private String[] format_type_info = new String[]{'format','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isVisibleByExternalUsers_type_info = new String[]{'isVisibleByExternalUsers','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] language_type_info = new String[]{'language','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] originNetwork_type_info = new String[]{'originNetwork','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] relationships_type_info = new String[]{'relationships','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] versions_type_info = new String[]{'versions','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'format','isVisibleByExternalUsers','language','masterLabel','originNetwork','relationships','versions'};
}