public class ContentAssetVersion {
    public String number_x;
    public String pathOnClient;
    public String zipEntry;
    private String[] number_x_type_info = new String[]{'number','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] pathOnClient_type_info = new String[]{'pathOnClient','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] zipEntry_type_info = new String[]{'zipEntry','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'number_x','pathOnClient','zipEntry'};
}