public class ApexTestSuite {
    public String[] testClassName;
    private String[] testClassName_type_info = new String[]{'testClassName','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'testClassName'};
}