public class ApexEmailNotifications {
    public ApexEmailNotification[] apexEmailNotification;
    private String[] apexEmailNotification_type_info = new String[]{'apexEmailNotification','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apexEmailNotification'};
}