public class ApexEmailNotification {
    public String email;
    public String user_x;
    private String[] email_type_info = new String[]{'email','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] user_x_type_info = new String[]{'user','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'email','user_x'};
}