public class KnowledgeAnswerSettings {
    public String assignTo;
    public String defaultArticleType;
    public Boolean enableArticleCreation;
    private String[] assignTo_type_info = new String[]{'assignTo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] defaultArticleType_type_info = new String[]{'defaultArticleType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableArticleCreation_type_info = new String[]{'enableArticleCreation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignTo','defaultArticleType','enableArticleCreation'};
}