public class KnowledgeCaseSettings {
    public String articlePDFCreationProfile;
    public KnowledgeCommunitiesSettings articlePublicSharingCommunities;
    public KnowledgeSitesSettings articlePublicSharingSites;
    public KnowledgeSitesSettings articlePublicSharingSitesChatterAnswers;
    public String assignTo;
    public String customizationClass;
    public String defaultContributionArticleType;
    public String editor;
    public Boolean enableArticleCreation;
    public Boolean enableArticlePublicSharingSites;
    public Boolean enableCaseDataCategoryMapping;
    public Boolean useProfileForPDFCreation;
    private String[] articlePDFCreationProfile_type_info = new String[]{'articlePDFCreationProfile','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] articlePublicSharingCommunities_type_info = new String[]{'articlePublicSharingCommunities','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] articlePublicSharingSites_type_info = new String[]{'articlePublicSharingSites','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] articlePublicSharingSitesChatterAnswers_type_info = new String[]{'articlePublicSharingSitesChatterAnswers','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] assignTo_type_info = new String[]{'assignTo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] customizationClass_type_info = new String[]{'customizationClass','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] defaultContributionArticleType_type_info = new String[]{'defaultContributionArticleType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] editor_type_info = new String[]{'editor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableArticleCreation_type_info = new String[]{'enableArticleCreation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableArticlePublicSharingSites_type_info = new String[]{'enableArticlePublicSharingSites','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCaseDataCategoryMapping_type_info = new String[]{'enableCaseDataCategoryMapping','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] useProfileForPDFCreation_type_info = new String[]{'useProfileForPDFCreation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'articlePDFCreationProfile','articlePublicSharingCommunities','articlePublicSharingSites','articlePublicSharingSitesChatterAnswers','assignTo','customizationClass','defaultContributionArticleType','editor','enableArticleCreation','enableArticlePublicSharingSites','enableCaseDataCategoryMapping','useProfileForPDFCreation'};
}