public class FieldSetItem {
    public String field;
    public Boolean isFieldManaged;
    public Boolean isRequired;
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isFieldManaged_type_info = new String[]{'isFieldManaged','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isRequired_type_info = new String[]{'isRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'field','isFieldManaged','isRequired'};
}