public class MktDataLakeFieldAttributes {
    public String dateFormat;
    public String definitionCreationType;
    public String externalName;
    public Boolean isEventDate;
    public Boolean isInternalOrganization;
    public Boolean isRecordModified;
    public Integer primaryIndexOrder;
    private String[] dateFormat_type_info = new String[]{'dateFormat','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] definitionCreationType_type_info = new String[]{'definitionCreationType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] externalName_type_info = new String[]{'externalName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isEventDate_type_info = new String[]{'isEventDate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isInternalOrganization_type_info = new String[]{'isInternalOrganization','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isRecordModified_type_info = new String[]{'isRecordModified','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] primaryIndexOrder_type_info = new String[]{'primaryIndexOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dateFormat','definitionCreationType','externalName','isEventDate','isInternalOrganization','isRecordModified','primaryIndexOrder'};
}