public class MktDataModelAttributes {
    public String creationType;
    public String dataModelTaxonomy;
    public Boolean isEnabled;
    public Boolean isSegmentable;
    public String objectCategory;
    public String referenceEntityGroup;
    public String referenceEntityName;
    public String referenceEntitySubjectArea;
    private String[] creationType_type_info = new String[]{'creationType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dataModelTaxonomy_type_info = new String[]{'dataModelTaxonomy','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isEnabled_type_info = new String[]{'isEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isSegmentable_type_info = new String[]{'isSegmentable','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] objectCategory_type_info = new String[]{'objectCategory','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] referenceEntityGroup_type_info = new String[]{'referenceEntityGroup','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] referenceEntityName_type_info = new String[]{'referenceEntityName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] referenceEntitySubjectArea_type_info = new String[]{'referenceEntitySubjectArea','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'creationType','dataModelTaxonomy','isEnabled','isSegmentable','objectCategory','referenceEntityGroup','referenceEntityName','referenceEntitySubjectArea'};
}