public class MktDataLakeAttributes {
    public String creationType;
    public String dataSource;
    public Boolean isEnabled;
    public String objectCategory;
    private String[] creationType_type_info = new String[]{'creationType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dataSource_type_info = new String[]{'dataSource','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isEnabled_type_info = new String[]{'isEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] objectCategory_type_info = new String[]{'objectCategory','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'creationType','dataSource','isEnabled','objectCategory'};
}