public class MktDataModelFieldAttributes {
    public String definitionCreationType;
    public String invalidMergeActionType;
    public Boolean isDynamicLookup;
    public Integer primaryIndexOrder;
    public String refAttrDeveloperName;
    private String[] definitionCreationType_type_info = new String[]{'definitionCreationType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] invalidMergeActionType_type_info = new String[]{'invalidMergeActionType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isDynamicLookup_type_info = new String[]{'isDynamicLookup','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] primaryIndexOrder_type_info = new String[]{'primaryIndexOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] refAttrDeveloperName_type_info = new String[]{'refAttrDeveloperName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'definitionCreationType','invalidMergeActionType','isDynamicLookup','primaryIndexOrder','refAttrDeveloperName'};
}