public class PlatformEventChannelMember {
    public EnrichedField[] enrichedFields;
    public String eventChannel;
    public String selectedEntity;
    private String[] enrichedFields_type_info = new String[]{'enrichedFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] eventChannel_type_info = new String[]{'eventChannel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] selectedEntity_type_info = new String[]{'selectedEntity','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enrichedFields','eventChannel','selectedEntity'};
}