public class ProfileSearchLayouts {
    public String[] fields;
    public String profileName;
    private String[] fields_type_info = new String[]{'fields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] profileName_type_info = new String[]{'profileName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'fields','profileName'};
}