public class SearchLayouts {
    public String[] customTabListAdditionalFields;
    public String[] excludedStandardButtons;
    public String[] listViewButtons;
    public String[] lookupDialogsAdditionalFields;
    public String[] lookupFilterFields;
    public String[] lookupPhoneDialogsAdditionalFields;
    public String[] massQuickActions;
    public String[] searchFilterFields;
    public String[] searchResultsAdditionalFields;
    public String[] searchResultsCustomButtons;
    private String[] customTabListAdditionalFields_type_info = new String[]{'customTabListAdditionalFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] excludedStandardButtons_type_info = new String[]{'excludedStandardButtons','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] listViewButtons_type_info = new String[]{'listViewButtons','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] lookupDialogsAdditionalFields_type_info = new String[]{'lookupDialogsAdditionalFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] lookupFilterFields_type_info = new String[]{'lookupFilterFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] lookupPhoneDialogsAdditionalFields_type_info = new String[]{'lookupPhoneDialogsAdditionalFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] massQuickActions_type_info = new String[]{'massQuickActions','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] searchFilterFields_type_info = new String[]{'searchFilterFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] searchResultsAdditionalFields_type_info = new String[]{'searchResultsAdditionalFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] searchResultsCustomButtons_type_info = new String[]{'searchResultsCustomButtons','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customTabListAdditionalFields','excludedStandardButtons','listViewButtons','lookupDialogsAdditionalFields','lookupFilterFields','lookupPhoneDialogsAdditionalFields','massQuickActions','searchFilterFields','searchResultsAdditionalFields','searchResultsCustomButtons'};
}