public class ValueSettings {
    public String[] controllingFieldValue;
    public String valueName;
    private String[] controllingFieldValue_type_info = new String[]{'controllingFieldValue','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] valueName_type_info = new String[]{'valueName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'controllingFieldValue','valueName'};
}