public class AccessMapping {
    public String accessLevel;
    public String object_x;
    public String objectField;
    public String userField;
    private String[] accessLevel_type_info = new String[]{'accessLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] object_x_type_info = new String[]{'object','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] objectField_type_info = new String[]{'objectField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] userField_type_info = new String[]{'userField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'accessLevel','object_x','objectField','userField'};
}