public class SharingGuestRule {
    public String booleanFilter;
    public FilterItem[] criteriaItems;
    public Boolean includeHVUOwnedRecords;
    private String[] booleanFilter_type_info = new String[]{'booleanFilter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] criteriaItems_type_info = new String[]{'criteriaItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] includeHVUOwnedRecords_type_info = new String[]{'includeHVUOwnedRecords','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'booleanFilter','criteriaItems','includeHVUOwnedRecords'};
}