public class AccountRelationshipShareRule {
    public String accessLevel;
    public String accountToCriteriaField;
    public String description;
    public String entityType;
    public String masterLabel;
    public String staticFormulaCriteria;
    public String type_x;
    private String[] accessLevel_type_info = new String[]{'accessLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] accountToCriteriaField_type_info = new String[]{'accountToCriteriaField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] entityType_type_info = new String[]{'entityType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] staticFormulaCriteria_type_info = new String[]{'staticFormulaCriteria','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'accessLevel','accountToCriteriaField','description','entityType','masterLabel','staticFormulaCriteria','type_x'};
}