public class BrandingSet {
    public BrandingSetProperty[] brandingSetProperty;
    public String description;
    public String masterLabel;
    public String type_x;
    private String[] brandingSetProperty_type_info = new String[]{'brandingSetProperty','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'brandingSetProperty','description','masterLabel','type_x'};
}