public class BrandingSetProperty {
    public String propertyName;
    public String propertyValue;
    private String[] propertyName_type_info = new String[]{'propertyName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] propertyValue_type_info = new String[]{'propertyValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'propertyName','propertyValue'};
}