public class ChatterExtension {
    public String compositionComponent;
    public String description;
    public String extensionName;
    public String headerText;
    public String hoverText;
    public String icon;
    public Boolean isProtected;
    public String masterLabel;
    public String renderComponent;
    public String type_x;
    private String[] compositionComponent_type_info = new String[]{'compositionComponent','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] extensionName_type_info = new String[]{'extensionName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] headerText_type_info = new String[]{'headerText','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] hoverText_type_info = new String[]{'hoverText','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] icon_type_info = new String[]{'icon','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isProtected_type_info = new String[]{'isProtected','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] renderComponent_type_info = new String[]{'renderComponent','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'compositionComponent','description','extensionName','headerText','hoverText','icon','isProtected','masterLabel','renderComponent','type_x'};
}