public class CommunityThemeRouteOverride {
    public String customThemeLayoutType;
    public String pageAttributes;
    public String pageType;
    public String themeLayoutType;
    private String[] customThemeLayoutType_type_info = new String[]{'customThemeLayoutType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] pageAttributes_type_info = new String[]{'pageAttributes','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] pageType_type_info = new String[]{'pageType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] themeLayoutType_type_info = new String[]{'themeLayoutType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customThemeLayoutType','pageAttributes','pageType','themeLayoutType'};
}