public class CommunityRoles {
    public String customerUserRole;
    public String employeeUserRole;
    public String partnerUserRole;
    private String[] customerUserRole_type_info = new String[]{'customerUserRole','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] employeeUserRole_type_info = new String[]{'employeeUserRole','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] partnerUserRole_type_info = new String[]{'partnerUserRole','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customerUserRole','employeeUserRole','partnerUserRole'};
}