public class CommunityTemplatePageSetting {
    public String page_x;
    public String themeLayout;
    private String[] page_x_type_info = new String[]{'page','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] themeLayout_type_info = new String[]{'themeLayout','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'page_x','themeLayout'};
}