public class CommunityThemeDefinition {
    public CommunityThemeBundleInfo[] bundlesInfo;
    public CommunityCustomThemeLayoutType[] customThemeLayoutType;
    public String defaultBrandingSet;
    public String description;
    public Boolean enableExtendedCleanUpOnDelete;
    public String masterLabel;
    public String publisher;
    public CommunityThemeRouteOverride[] themeRouteOverride;
    public CommunityThemeSetting[] themeSetting;
    private String[] bundlesInfo_type_info = new String[]{'bundlesInfo','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] customThemeLayoutType_type_info = new String[]{'customThemeLayoutType','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] defaultBrandingSet_type_info = new String[]{'defaultBrandingSet','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableExtendedCleanUpOnDelete_type_info = new String[]{'enableExtendedCleanUpOnDelete','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] publisher_type_info = new String[]{'publisher','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] themeRouteOverride_type_info = new String[]{'themeRouteOverride','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] themeSetting_type_info = new String[]{'themeSetting','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'bundlesInfo','customThemeLayoutType','defaultBrandingSet','description','enableExtendedCleanUpOnDelete','masterLabel','publisher','themeRouteOverride','themeSetting'};
}