public class CommunityTemplateDefinition {
    public String baseTemplate;
    public CommunityTemplateBundleInfo[] bundlesInfo;
    public String category;
    public String defaultBrandingSet;
    public String defaultThemeDefinition;
    public String description;
    public Boolean enableExtendedCleanUpOnDelete;
    public String masterLabel;
    public NavigationLinkSet[] navigationLinkSet;
    public CommunityTemplatePageSetting[] pageSetting;
    public String publisher;
    private String[] baseTemplate_type_info = new String[]{'baseTemplate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] bundlesInfo_type_info = new String[]{'bundlesInfo','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] category_type_info = new String[]{'category','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] defaultBrandingSet_type_info = new String[]{'defaultBrandingSet','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] defaultThemeDefinition_type_info = new String[]{'defaultThemeDefinition','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableExtendedCleanUpOnDelete_type_info = new String[]{'enableExtendedCleanUpOnDelete','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] navigationLinkSet_type_info = new String[]{'navigationLinkSet','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] pageSetting_type_info = new String[]{'pageSetting','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] publisher_type_info = new String[]{'publisher','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'baseTemplate','bundlesInfo','category','defaultBrandingSet','defaultThemeDefinition','description','enableExtendedCleanUpOnDelete','masterLabel','navigationLinkSet','pageSetting','publisher'};
}