public class CommunityThemeSetting {
    public String customThemeLayoutType;
    public String themeLayout;
    public String themeLayoutType;
    private String[] customThemeLayoutType_type_info = new String[]{'customThemeLayoutType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] themeLayout_type_info = new String[]{'themeLayout','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] themeLayoutType_type_info = new String[]{'themeLayoutType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customThemeLayoutType','themeLayout','themeLayoutType'};
}