public class ExperienceResource {
    public String fileName;
    public String format;
    public String source;
    public String type_x;
    private String[] fileName_type_info = new String[]{'fileName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] format_type_info = new String[]{'format','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] source_type_info = new String[]{'source','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'fileName','format','source','type_x'};
}