public class ExperienceBundle {
    public ExperienceResources experienceResources;
    public String label;
    public String type_x;
    public String urlPathPrefix;
    private String[] experienceResources_type_info = new String[]{'experienceResources','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] urlPathPrefix_type_info = new String[]{'urlPathPrefix','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'experienceResources','label','type_x','urlPathPrefix'};
}