public class NavigationMenuItem {
    public String defaultListViewId;
    public String label;
    public NavigationMenuItemBranding menuItemBranding;
    public Integer position;
    public Boolean publiclyAvailable;
    public NavigationSubMenu subMenu;
    public String target;
    public String targetPreference;
    public String type_x;
    private String[] defaultListViewId_type_info = new String[]{'defaultListViewId','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] menuItemBranding_type_info = new String[]{'menuItemBranding','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] position_type_info = new String[]{'position','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] publiclyAvailable_type_info = new String[]{'publiclyAvailable','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] subMenu_type_info = new String[]{'subMenu','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] target_type_info = new String[]{'target','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] targetPreference_type_info = new String[]{'targetPreference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'defaultListViewId','label','menuItemBranding','position','publiclyAvailable','subMenu','target','targetPreference','type_x'};
}