public class NetworkMemberGroup {
    public String[] permissionSet;
    public String[] profile;
    private String[] permissionSet_type_info = new String[]{'permissionSet','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] profile_type_info = new String[]{'profile','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'permissionSet','profile'};
}