public class NetworkTabSet {
    public String[] customTab;
    public String defaultTab;
    public String[] standardTab;
    private String[] customTab_type_info = new String[]{'customTab','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] defaultTab_type_info = new String[]{'defaultTab','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] standardTab_type_info = new String[]{'standardTab','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customTab','defaultTab','standardTab'};
}