public class NetworkPageOverride {
    public String changePasswordPageOverrideSetting;
    public String forgotPasswordPageOverrideSetting;
    public String homePageOverrideSetting;
    public String loginPageOverrideSetting;
    public String selfRegProfilePageOverrideSetting;
    private String[] changePasswordPageOverrideSetting_type_info = new String[]{'changePasswordPageOverrideSetting','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] forgotPasswordPageOverrideSetting_type_info = new String[]{'forgotPasswordPageOverrideSetting','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] homePageOverrideSetting_type_info = new String[]{'homePageOverrideSetting','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] loginPageOverrideSetting_type_info = new String[]{'loginPageOverrideSetting','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] selfRegProfilePageOverrideSetting_type_info = new String[]{'selfRegProfilePageOverrideSetting','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'changePasswordPageOverrideSetting','forgotPasswordPageOverrideSetting','homePageOverrideSetting','loginPageOverrideSetting','selfRegProfilePageOverrideSetting'};
}