public class CustomPermissionDependencyRequired {
    public String customPermission;
    public Boolean dependency;
    private String[] customPermission_type_info = new String[]{'customPermission','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] dependency_type_info = new String[]{'dependency','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customPermission','dependency'};
}