public class InstalledPackage {
    public Boolean activateRSS;
    public String password;
    public String versionNumber;
    private String[] activateRSS_type_info = new String[]{'activateRSS','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] password_type_info = new String[]{'password','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] versionNumber_type_info = new String[]{'versionNumber','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'activateRSS','password','versionNumber'};
}