public class AccountSettings {
    public Boolean enableAccountHistoryTracking;
    public Boolean enableAccountInsightsInMobile;
    public Boolean enableAccountOwnerReport;
    public Boolean enableAccountTeams;
    public Boolean enableContactHistoryTracking;
    public Boolean enableRelateContactToMultipleAccounts;
    public Boolean showViewHierarchyLink;
    private String[] enableAccountHistoryTracking_type_info = new String[]{'enableAccountHistoryTracking','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAccountInsightsInMobile_type_info = new String[]{'enableAccountInsightsInMobile','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAccountOwnerReport_type_info = new String[]{'enableAccountOwnerReport','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAccountTeams_type_info = new String[]{'enableAccountTeams','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableContactHistoryTracking_type_info = new String[]{'enableContactHistoryTracking','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableRelateContactToMultipleAccounts_type_info = new String[]{'enableRelateContactToMultipleAccounts','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showViewHierarchyLink_type_info = new String[]{'showViewHierarchyLink','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableAccountHistoryTracking','enableAccountInsightsInMobile','enableAccountOwnerReport','enableAccountTeams','enableContactHistoryTracking','enableRelateContactToMultipleAccounts','showViewHierarchyLink'};
}