public class ActionsSettings {
    public Boolean enableDefaultQuickActionsOn;
    public Boolean enableMdpEnabled;
    public Boolean enableOfflineWebLinks;
    public Boolean enableThirdPartyActions;
    private String[] enableDefaultQuickActionsOn_type_info = new String[]{'enableDefaultQuickActionsOn','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMdpEnabled_type_info = new String[]{'enableMdpEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOfflineWebLinks_type_info = new String[]{'enableOfflineWebLinks','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableThirdPartyActions_type_info = new String[]{'enableThirdPartyActions','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableDefaultQuickActionsOn','enableMdpEnabled','enableOfflineWebLinks','enableThirdPartyActions'};
}