public class AppSettings {
    public String connectedAppName;
    public Boolean enabled;
    private String[] connectedAppName_type_info = new String[]{'connectedAppName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enabled_type_info = new String[]{'enabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'connectedAppName','enabled'};
}