public class BusinessHoursSettings {
    public BusinessHoursEntry[] businessHours;
    public Holiday[] holidays;
    private String[] businessHours_type_info = new String[]{'businessHours','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] holidays_type_info = new String[]{'holidays','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'businessHours','holidays'};
}