public class CampaignSettings {
    public Integer aiAttributionTimeframe;
    public Boolean enableAIAttribution;
    public Boolean enableAccountsAsCM;
    public Boolean enableAutoCampInfluenceDisabled;
    public Boolean enableB2bmaCampaignInfluence2;
    public Boolean enableCampaignHistoryTrackEnabled;
    public Boolean enableCampaignInfluence2;
    public Boolean enableCampaignMemberTWCF;
    public Boolean enableEKAI;
    public Boolean enableSuppressNoValueCI2;
    private String[] aiAttributionTimeframe_type_info = new String[]{'aiAttributionTimeframe','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAIAttribution_type_info = new String[]{'enableAIAttribution','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAccountsAsCM_type_info = new String[]{'enableAccountsAsCM','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAutoCampInfluenceDisabled_type_info = new String[]{'enableAutoCampInfluenceDisabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableB2bmaCampaignInfluence2_type_info = new String[]{'enableB2bmaCampaignInfluence2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCampaignHistoryTrackEnabled_type_info = new String[]{'enableCampaignHistoryTrackEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCampaignInfluence2_type_info = new String[]{'enableCampaignInfluence2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCampaignMemberTWCF_type_info = new String[]{'enableCampaignMemberTWCF','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEKAI_type_info = new String[]{'enableEKAI','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSuppressNoValueCI2_type_info = new String[]{'enableSuppressNoValueCI2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'aiAttributionTimeframe','enableAIAttribution','enableAccountsAsCM','enableAutoCampInfluenceDisabled','enableB2bmaCampaignInfluence2','enableCampaignHistoryTrackEnabled','enableCampaignInfluence2','enableCampaignMemberTWCF','enableEKAI','enableSuppressNoValueCI2'};
}