public class ChatterEmailsMDSettings {
    public Boolean enableChatterDigestEmailsApiOnly;
    public Boolean enableChatterEmailAttachment;
    public Boolean enableCollaborationEmail;
    public Boolean enableDisplayAppDownloadBadges;
    public Boolean enableEmailReplyToChatter;
    public Boolean enableEmailToChatter;
    public Boolean noQnOwnNotifyOnCaseCmt;
    public Boolean noQnOwnNotifyOnRep;
    public Boolean noQnSubNotifyOnBestR;
    public Boolean noQnSubNotifyOnRep;
    private String[] enableChatterDigestEmailsApiOnly_type_info = new String[]{'enableChatterDigestEmailsApiOnly','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableChatterEmailAttachment_type_info = new String[]{'enableChatterEmailAttachment','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCollaborationEmail_type_info = new String[]{'enableCollaborationEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDisplayAppDownloadBadges_type_info = new String[]{'enableDisplayAppDownloadBadges','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEmailReplyToChatter_type_info = new String[]{'enableEmailReplyToChatter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEmailToChatter_type_info = new String[]{'enableEmailToChatter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] noQnOwnNotifyOnCaseCmt_type_info = new String[]{'noQnOwnNotifyOnCaseCmt','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] noQnOwnNotifyOnRep_type_info = new String[]{'noQnOwnNotifyOnRep','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] noQnSubNotifyOnBestR_type_info = new String[]{'noQnSubNotifyOnBestR','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] noQnSubNotifyOnRep_type_info = new String[]{'noQnSubNotifyOnRep','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableChatterDigestEmailsApiOnly','enableChatterEmailAttachment','enableCollaborationEmail','enableDisplayAppDownloadBadges','enableEmailReplyToChatter','enableEmailToChatter','noQnOwnNotifyOnCaseCmt','noQnOwnNotifyOnRep','noQnSubNotifyOnBestR','noQnSubNotifyOnRep'};
}