public class ChatterAnswersSettings {
    public Boolean emailFollowersOnBestAnswer;
    public Boolean emailFollowersOnReply;
    public Boolean emailOwnerOnPrivateReply;
    public Boolean emailOwnerOnReply;
    public Boolean enableAnswerViaEmail;
    public Boolean enableChatterAnswers;
    public Boolean enableFacebookSSO;
    public Boolean enableInlinePublisher;
    public Boolean enableReputation;
    public Boolean enableRichTextEditor;
    public String facebookAuthProvider;
    public Boolean showInPortals;
    private String[] emailFollowersOnBestAnswer_type_info = new String[]{'emailFollowersOnBestAnswer','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] emailFollowersOnReply_type_info = new String[]{'emailFollowersOnReply','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] emailOwnerOnPrivateReply_type_info = new String[]{'emailOwnerOnPrivateReply','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] emailOwnerOnReply_type_info = new String[]{'emailOwnerOnReply','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAnswerViaEmail_type_info = new String[]{'enableAnswerViaEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableChatterAnswers_type_info = new String[]{'enableChatterAnswers','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableFacebookSSO_type_info = new String[]{'enableFacebookSSO','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableInlinePublisher_type_info = new String[]{'enableInlinePublisher','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableReputation_type_info = new String[]{'enableReputation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableRichTextEditor_type_info = new String[]{'enableRichTextEditor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] facebookAuthProvider_type_info = new String[]{'facebookAuthProvider','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showInPortals_type_info = new String[]{'showInPortals','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'emailFollowersOnBestAnswer','emailFollowersOnReply','emailOwnerOnPrivateReply','emailOwnerOnReply','enableAnswerViaEmail','enableChatterAnswers','enableFacebookSSO','enableInlinePublisher','enableReputation','enableRichTextEditor','facebookAuthProvider','showInPortals'};
}