public class CompanySettings {
    public Boolean enableCustomFiscalYear;
    public FiscalYearSettings fiscalYear;
    private String[] enableCustomFiscalYear_type_info = new String[]{'enableCustomFiscalYear','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] fiscalYear_type_info = new String[]{'fiscalYear','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCustomFiscalYear','fiscalYear'};
}