public class ConnectedAppSettings {
    public Boolean enableAdminApprovedAppsOnly;
    public Boolean enableAdminApprovedAppsOnlyForExternalUser;
    public Boolean enableSkipUserProvisioningWizardWelcomePage;
    private String[] enableAdminApprovedAppsOnly_type_info = new String[]{'enableAdminApprovedAppsOnly','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAdminApprovedAppsOnlyForExternalUser_type_info = new String[]{'enableAdminApprovedAppsOnlyForExternalUser','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSkipUserProvisioningWizardWelcomePage_type_info = new String[]{'enableSkipUserProvisioningWizardWelcomePage','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableAdminApprovedAppsOnly','enableAdminApprovedAppsOnlyForExternalUser','enableSkipUserProvisioningWizardWelcomePage'};
}