public class CurrencySettings {
    public Boolean enableCurrencyEffectiveDates;
    public Boolean enableCurrencySymbolWithMultiCurrency;
    public Boolean enableMultiCurrency;
    public Boolean isMultiCurrencyActivationAllowed;
    public Boolean isParenCurrencyConvDisabled;
    private String[] enableCurrencyEffectiveDates_type_info = new String[]{'enableCurrencyEffectiveDates','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCurrencySymbolWithMultiCurrency_type_info = new String[]{'enableCurrencySymbolWithMultiCurrency','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMultiCurrency_type_info = new String[]{'enableMultiCurrency','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isMultiCurrencyActivationAllowed_type_info = new String[]{'isMultiCurrencyActivationAllowed','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isParenCurrencyConvDisabled_type_info = new String[]{'isParenCurrencyConvDisabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCurrencyEffectiveDates','enableCurrencySymbolWithMultiCurrency','enableMultiCurrency','isMultiCurrencyActivationAllowed','isParenCurrencyConvDisabled'};
}