public class DevHubSettings {
    public Boolean enableDevOpsCenter;
    public Boolean enablePackaging2;
    public Boolean enableScratchOrgManagementPref;
    public Boolean enableShapeExportPref;
    private String[] enableDevOpsCenter_type_info = new String[]{'enableDevOpsCenter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enablePackaging2_type_info = new String[]{'enablePackaging2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableScratchOrgManagementPref_type_info = new String[]{'enableScratchOrgManagementPref','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableShapeExportPref_type_info = new String[]{'enableShapeExportPref','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableDevOpsCenter','enablePackaging2','enableScratchOrgManagementPref','enableShapeExportPref'};
}