public class EmailToCaseSettings {
    public Boolean enableE2CAttachmentAsFile;
    public Boolean enableE2CSourceTracking;
    public Boolean enableEmailToCase;
    public Boolean enableHtmlEmail;
    public Boolean enableOnDemandEmailToCase;
    public Boolean enableThreadIDInBody;
    public Boolean enableThreadIDInSubject;
    public Boolean notifyOwnerOnNewCaseEmail;
    public String overEmailLimitAction;
    public Boolean preQuoteSignature;
    public EmailToCaseRoutingAddress[] routingAddresses;
    public String unauthorizedSenderAction;
    private String[] enableE2CAttachmentAsFile_type_info = new String[]{'enableE2CAttachmentAsFile','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableE2CSourceTracking_type_info = new String[]{'enableE2CSourceTracking','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEmailToCase_type_info = new String[]{'enableEmailToCase','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableHtmlEmail_type_info = new String[]{'enableHtmlEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOnDemandEmailToCase_type_info = new String[]{'enableOnDemandEmailToCase','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableThreadIDInBody_type_info = new String[]{'enableThreadIDInBody','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableThreadIDInSubject_type_info = new String[]{'enableThreadIDInSubject','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] notifyOwnerOnNewCaseEmail_type_info = new String[]{'notifyOwnerOnNewCaseEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] overEmailLimitAction_type_info = new String[]{'overEmailLimitAction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] preQuoteSignature_type_info = new String[]{'preQuoteSignature','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] routingAddresses_type_info = new String[]{'routingAddresses','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] unauthorizedSenderAction_type_info = new String[]{'unauthorizedSenderAction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableE2CAttachmentAsFile','enableE2CSourceTracking','enableEmailToCase','enableHtmlEmail','enableOnDemandEmailToCase','enableThreadIDInBody','enableThreadIDInSubject','notifyOwnerOnNewCaseEmail','overEmailLimitAction','preQuoteSignature','routingAddresses','unauthorizedSenderAction'};
}