public class EncryptionKeySettings {
    public Boolean canOptOutOfDerivationWithBYOK;
    public Boolean enableCacheOnlyKeys;
    public Boolean enableReplayDetection;
    private String[] canOptOutOfDerivationWithBYOK_type_info = new String[]{'canOptOutOfDerivationWithBYOK','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableCacheOnlyKeys_type_info = new String[]{'enableCacheOnlyKeys','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableReplayDetection_type_info = new String[]{'enableReplayDetection','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'canOptOutOfDerivationWithBYOK','enableCacheOnlyKeys','enableReplayDetection'};
}