public class EventSettings {
    public Boolean enableApexLimitEvents;
    public Boolean enableDeleteMonitoringData;
    public Boolean enableDynamicStreamingChannel;
    public Boolean enableEventLogWaveIntegration;
    public Boolean enableLoginForensics;
    public Boolean enableStreamingApi;
    public Boolean enableTerminateOldestSession;
    public Boolean enableTransactionSecurityPolicies;
    private String[] enableApexLimitEvents_type_info = new String[]{'enableApexLimitEvents','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDeleteMonitoringData_type_info = new String[]{'enableDeleteMonitoringData','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDynamicStreamingChannel_type_info = new String[]{'enableDynamicStreamingChannel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEventLogWaveIntegration_type_info = new String[]{'enableEventLogWaveIntegration','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableLoginForensics_type_info = new String[]{'enableLoginForensics','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableStreamingApi_type_info = new String[]{'enableStreamingApi','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableTerminateOldestSession_type_info = new String[]{'enableTerminateOldestSession','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableTransactionSecurityPolicies_type_info = new String[]{'enableTransactionSecurityPolicies','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableApexLimitEvents','enableDeleteMonitoringData','enableDynamicStreamingChannel','enableEventLogWaveIntegration','enableLoginForensics','enableStreamingApi','enableTerminateOldestSession','enableTransactionSecurityPolicies'};
}