public class ExperienceBundleSettings {
    public Boolean enableExperienceBundleMetadata;
    private String[] enableExperienceBundleMetadata_type_info = new String[]{'enableExperienceBundleMetadata','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableExperienceBundleMetadata'};
}