public class FeedItemSettings {
    public Integer characterLimit;
    public String displayFormat;
    public String feedItemType;
    private String[] characterLimit_type_info = new String[]{'characterLimit','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] displayFormat_type_info = new String[]{'displayFormat','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] feedItemType_type_info = new String[]{'feedItemType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'characterLimit','displayFormat','feedItemType'};
}