public class FilesConnectSettings {
    public Boolean enableContentHubAllowed;
    public Boolean enableContentHubCvtLinksAllowed;
    public Boolean enableContentHubEOSearchLayout;
    private String[] enableContentHubAllowed_type_info = new String[]{'enableContentHubAllowed','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableContentHubCvtLinksAllowed_type_info = new String[]{'enableContentHubCvtLinksAllowed','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableContentHubEOSearchLayout_type_info = new String[]{'enableContentHubEOSearchLayout','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableContentHubAllowed','enableContentHubCvtLinksAllowed','enableContentHubEOSearchLayout'};
}