public class FileUploadAndDownloadSecuritySettings {
    public FileTypeDispositionAssignmentBean[] dispositions;
    public Boolean noHtmlUploadAsAttachment;
    private String[] dispositions_type_info = new String[]{'dispositions','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] noHtmlUploadAsAttachment_type_info = new String[]{'noHtmlUploadAsAttachment','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dispositions','noHtmlUploadAsAttachment'};
}