public class FindSimilarOppFilter {
    public String[] similarOpportunitiesDisplayColumns;
    public String[] similarOpportunitiesMatchFields;
    private String[] similarOpportunitiesDisplayColumns_type_info = new String[]{'similarOpportunitiesDisplayColumns','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] similarOpportunitiesMatchFields_type_info = new String[]{'similarOpportunitiesMatchFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'similarOpportunitiesDisplayColumns','similarOpportunitiesMatchFields'};
}