public class FiscalYearSettings {
    public String fiscalYearNameBasedOn;
    public String startMonth;
    private String[] fiscalYearNameBasedOn_type_info = new String[]{'fiscalYearNameBasedOn','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] startMonth_type_info = new String[]{'startMonth','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'fiscalYearNameBasedOn','startMonth'};
}