public class FormulaSettings {
    public Boolean enableDSTAwareDatevalue;
    private String[] enableDSTAwareDatevalue_type_info = new String[]{'enableDSTAwareDatevalue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableDSTAwareDatevalue'};
}