public class GoogleAppsSettings {
    public Boolean enableGmailButtons;
    public Boolean enableGmailButtonsAndLinks;
    public Boolean enableGmailLinks;
    public Boolean enableGoogleDocs;
    public Boolean enableGoogleDocsTab;
    public Boolean enableGoogleTalk;
    public String googleAppsDomain;
    public Boolean googleAppsDomainLinked;
    public Boolean googleAppsDomainValidated;
    private String[] enableGmailButtons_type_info = new String[]{'enableGmailButtons','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableGmailButtonsAndLinks_type_info = new String[]{'enableGmailButtonsAndLinks','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableGmailLinks_type_info = new String[]{'enableGmailLinks','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableGoogleDocs_type_info = new String[]{'enableGoogleDocs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableGoogleDocsTab_type_info = new String[]{'enableGoogleDocsTab','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableGoogleTalk_type_info = new String[]{'enableGoogleTalk','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] googleAppsDomain_type_info = new String[]{'googleAppsDomain','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] googleAppsDomainLinked_type_info = new String[]{'googleAppsDomainLinked','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] googleAppsDomainValidated_type_info = new String[]{'googleAppsDomainValidated','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableGmailButtons','enableGmailButtonsAndLinks','enableGmailLinks','enableGoogleDocs','enableGoogleDocsTab','enableGoogleTalk','googleAppsDomain','googleAppsDomainLinked','googleAppsDomainValidated'};
}