public class LanguageSettings {
    public Boolean enableCanadaIcuFormat;
    public Boolean enableDataTranslation;
    public Boolean enableEndUserLanguages;
    public Boolean enableICULocaleDateFormat;
    public Boolean enableLocalNamesForStdObjects;
    public Boolean enablePlatformLanguages;
    public Boolean enableTranslationWorkbench;
    public Boolean useLanguageFallback;
    private String[] enableCanadaIcuFormat_type_info = new String[]{'enableCanadaIcuFormat','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDataTranslation_type_info = new String[]{'enableDataTranslation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEndUserLanguages_type_info = new String[]{'enableEndUserLanguages','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableICULocaleDateFormat_type_info = new String[]{'enableICULocaleDateFormat','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableLocalNamesForStdObjects_type_info = new String[]{'enableLocalNamesForStdObjects','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enablePlatformLanguages_type_info = new String[]{'enablePlatformLanguages','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableTranslationWorkbench_type_info = new String[]{'enableTranslationWorkbench','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] useLanguageFallback_type_info = new String[]{'useLanguageFallback','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCanadaIcuFormat','enableDataTranslation','enableEndUserLanguages','enableICULocaleDateFormat','enableLocalNamesForStdObjects','enablePlatformLanguages','enableTranslationWorkbench','useLanguageFallback'};
}