public class LeadConvertSettings {
    public Boolean allowOwnerChange;
    public ObjectMapping[] objectMapping;
    public String opportunityCreationOptions;
    private String[] allowOwnerChange_type_info = new String[]{'allowOwnerChange','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] objectMapping_type_info = new String[]{'objectMapping','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] opportunityCreationOptions_type_info = new String[]{'opportunityCreationOptions','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'allowOwnerChange','objectMapping','opportunityCreationOptions'};
}