public class LeadConfigSettings {
    public Boolean doesEnableLeadConvertDefaultSubjectBlankTaskCreation;
    public Boolean doesHideOpportunityInConvertLeadWindow;
    public Boolean doesPreserveLeadStatus;
    public Boolean doesSelectNoOpportunityOnConvertLead;
    public Boolean doesTrackHistory;
    public Boolean enableConversionsOnMobile;
    public Boolean enableOrgWideMergeAndDelete;
    public Boolean shouldLeadConvertRequireValidation;
    public Boolean shouldSendNotificationEmailWhenLeadOwnerUpdatesViaApexInLEX;
    private String[] doesEnableLeadConvertDefaultSubjectBlankTaskCreation_type_info = new String[]{'doesEnableLeadConvertDefaultSubjectBlankTaskCreation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesHideOpportunityInConvertLeadWindow_type_info = new String[]{'doesHideOpportunityInConvertLeadWindow','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesPreserveLeadStatus_type_info = new String[]{'doesPreserveLeadStatus','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesSelectNoOpportunityOnConvertLead_type_info = new String[]{'doesSelectNoOpportunityOnConvertLead','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesTrackHistory_type_info = new String[]{'doesTrackHistory','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableConversionsOnMobile_type_info = new String[]{'enableConversionsOnMobile','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOrgWideMergeAndDelete_type_info = new String[]{'enableOrgWideMergeAndDelete','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] shouldLeadConvertRequireValidation_type_info = new String[]{'shouldLeadConvertRequireValidation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] shouldSendNotificationEmailWhenLeadOwnerUpdatesViaApexInLEX_type_info = new String[]{'shouldSendNotificationEmailWhenLeadOwnerUpdatesViaApexInLEX','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'doesEnableLeadConvertDefaultSubjectBlankTaskCreation','doesHideOpportunityInConvertLeadWindow','doesPreserveLeadStatus','doesSelectNoOpportunityOnConvertLead','doesTrackHistory','enableConversionsOnMobile','enableOrgWideMergeAndDelete','shouldLeadConvertRequireValidation','shouldSendNotificationEmailWhenLeadOwnerUpdatesViaApexInLEX'};
}