public class MobileSettings {
    public DashboardMobileSettings dashboardMobile;
    public Boolean enableImportContactFromDevice;
    public Boolean enableNewSalesforceMobileAppForTablet;
    public Boolean enableNewSalesforceMobileAppForTabletWideScreen;
    public Boolean enableOfflineDraftsEnabled;
    public Boolean enablePopulateNameManuallyInToday;
    public Boolean enableS1EncryptedStoragePref2;
    public Boolean enableS1OfflinePref;
    private String[] dashboardMobile_type_info = new String[]{'dashboardMobile','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableImportContactFromDevice_type_info = new String[]{'enableImportContactFromDevice','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNewSalesforceMobileAppForTablet_type_info = new String[]{'enableNewSalesforceMobileAppForTablet','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNewSalesforceMobileAppForTabletWideScreen_type_info = new String[]{'enableNewSalesforceMobileAppForTabletWideScreen','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOfflineDraftsEnabled_type_info = new String[]{'enableOfflineDraftsEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enablePopulateNameManuallyInToday_type_info = new String[]{'enablePopulateNameManuallyInToday','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableS1EncryptedStoragePref2_type_info = new String[]{'enableS1EncryptedStoragePref2','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableS1OfflinePref_type_info = new String[]{'enableS1OfflinePref','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dashboardMobile','enableImportContactFromDevice','enableNewSalesforceMobileAppForTablet','enableNewSalesforceMobileAppForTabletWideScreen','enableOfflineDraftsEnabled','enablePopulateNameManuallyInToday','enableS1EncryptedStoragePref2','enableS1OfflinePref'};
}