public class MyDomainSettings {
    public Boolean canOnlyLoginWithMyDomainUrl;
    public Boolean doesApiLoginRequireOrgDomain;
    public Boolean enableNativeBrowserForAuthOnAndroid;
    public Boolean enableNativeBrowserForAuthOnIos;
    public String myDomainName;
    public String myDomainSuffix;
    public Boolean use3rdPartyCookieBlockingCompatibleHostnames;
    public Boolean useEdge;
    public Boolean useStabilizedMyDomainHostnames;
    public Boolean useStabilizedSandboxMyDomainHostnames;
    private String[] canOnlyLoginWithMyDomainUrl_type_info = new String[]{'canOnlyLoginWithMyDomainUrl','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] doesApiLoginRequireOrgDomain_type_info = new String[]{'doesApiLoginRequireOrgDomain','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNativeBrowserForAuthOnAndroid_type_info = new String[]{'enableNativeBrowserForAuthOnAndroid','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNativeBrowserForAuthOnIos_type_info = new String[]{'enableNativeBrowserForAuthOnIos','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] myDomainName_type_info = new String[]{'myDomainName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] myDomainSuffix_type_info = new String[]{'myDomainSuffix','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] use3rdPartyCookieBlockingCompatibleHostnames_type_info = new String[]{'use3rdPartyCookieBlockingCompatibleHostnames','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] useEdge_type_info = new String[]{'useEdge','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] useStabilizedMyDomainHostnames_type_info = new String[]{'useStabilizedMyDomainHostnames','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] useStabilizedSandboxMyDomainHostnames_type_info = new String[]{'useStabilizedSandboxMyDomainHostnames','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'canOnlyLoginWithMyDomainUrl','doesApiLoginRequireOrgDomain','enableNativeBrowserForAuthOnAndroid','enableNativeBrowserForAuthOnIos','myDomainName','myDomainSuffix','use3rdPartyCookieBlockingCompatibleHostnames','useEdge','useStabilizedMyDomainHostnames','useStabilizedSandboxMyDomainHostnames'};
}