public class NameSettings {
    public Boolean enableInformalName;
    public Boolean enableMiddleName;
    public Boolean enableNameSuffix;
    private String[] enableInformalName_type_info = new String[]{'enableInformalName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMiddleName_type_info = new String[]{'enableMiddleName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNameSuffix_type_info = new String[]{'enableNameSuffix','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableInformalName','enableMiddleName','enableNameSuffix'};
}