public class NotificationsSettings {
    public Boolean enableActvityReminderBrowserNotifs;
    public Boolean enableMobileAppPushNotifications;
    public Boolean enableNotifications;
    private String[] enableActvityReminderBrowserNotifs_type_info = new String[]{'enableActvityReminderBrowserNotifs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMobileAppPushNotifications_type_info = new String[]{'enableMobileAppPushNotifications','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNotifications_type_info = new String[]{'enableNotifications','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableActvityReminderBrowserNotifs','enableMobileAppPushNotifications','enableNotifications'};
}
