public class NotificationChannels {
    public Boolean desktopEnabled;
    public Boolean mobileEnabled;
    public Boolean slackEnabled;
    private String[] desktopEnabled_type_info = new String[]{'desktopEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] mobileEnabled_type_info = new String[]{'mobileEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] slackEnabled_type_info = new String[]{'slackEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'desktopEnabled','mobileEnabled','slackEnabled'};
}