public class ObjectSearchSetting {
    public Boolean enhancedLookupEnabled;
    public Boolean lookupAutoCompleteEnabled;
    public String name;
    public Integer resultsPerPageCount;
    private String[] enhancedLookupEnabled_type_info = new String[]{'enhancedLookupEnabled','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] lookupAutoCompleteEnabled_type_info = new String[]{'lookupAutoCompleteEnabled','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] resultsPerPageCount_type_info = new String[]{'resultsPerPageCount','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enhancedLookupEnabled','lookupAutoCompleteEnabled','name','resultsPerPageCount'};
}