public class OrderSettings {
    public Boolean enableEnhancedCommerceOrders;
    public Boolean enableNegativeQuantity;
    public Boolean enableOptionalPricebook;
    public Boolean enableOrderEvents;
    public Boolean enableOrders;
    public Boolean enableReductionOrders;
    public Boolean enableZeroQuantity;
    private String[] enableEnhancedCommerceOrders_type_info = new String[]{'enableEnhancedCommerceOrders','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableNegativeQuantity_type_info = new String[]{'enableNegativeQuantity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOptionalPricebook_type_info = new String[]{'enableOptionalPricebook','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOrderEvents_type_info = new String[]{'enableOrderEvents','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOrders_type_info = new String[]{'enableOrders','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableReductionOrders_type_info = new String[]{'enableReductionOrders','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableZeroQuantity_type_info = new String[]{'enableZeroQuantity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableEnhancedCommerceOrders','enableNegativeQuantity','enableOptionalPricebook','enableOrderEvents','enableOrders','enableReductionOrders','enableZeroQuantity'};
}