public class OrgSettings {
    public Boolean enableCustomerSuccessPortal;
    public Boolean enableIncludeContractStatus;
    public Boolean enableMakeDeploymentsMandatory;
    public Boolean enableManageSelfServiceUsers;
    public Boolean enableOrgFeedSentimentAnalysis;
    public Boolean enableRADeploymentAttributeOnly;
    public Boolean enableResetDivisionOnLogin;
    private String[] enableCustomerSuccessPortal_type_info = new String[]{'enableCustomerSuccessPortal','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableIncludeContractStatus_type_info = new String[]{'enableIncludeContractStatus','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMakeDeploymentsMandatory_type_info = new String[]{'enableMakeDeploymentsMandatory','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableManageSelfServiceUsers_type_info = new String[]{'enableManageSelfServiceUsers','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableOrgFeedSentimentAnalysis_type_info = new String[]{'enableOrgFeedSentimentAnalysis','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableRADeploymentAttributeOnly_type_info = new String[]{'enableRADeploymentAttributeOnly','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableResetDivisionOnLogin_type_info = new String[]{'enableResetDivisionOnLogin','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCustomerSuccessPortal','enableIncludeContractStatus','enableMakeDeploymentsMandatory','enableManageSelfServiceUsers','enableOrgFeedSentimentAnalysis','enableRADeploymentAttributeOnly','enableResetDivisionOnLogin'};
}