public class PathAssistantSettings {
    public Boolean canOverrideAutoPathCollapseWithUserPref;
    public Boolean pathAssistantEnabled;
    private String[] canOverrideAutoPathCollapseWithUserPref_type_info = new String[]{'canOverrideAutoPathCollapseWithUserPref','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] pathAssistantEnabled_type_info = new String[]{'pathAssistantEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'canOverrideAutoPathCollapseWithUserPref','pathAssistantEnabled'};
}