public class PicklistSettings {
    public Boolean isPicklistApiNameEditDisabled;
    private String[] isPicklistApiNameEditDisabled_type_info = new String[]{'isPicklistApiNameEditDisabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'isPicklistApiNameEditDisabled'};
}