public class PlatformEncryptionSettings {
    public Boolean canEncryptManagedPackageFields;
    public Boolean enableDeterministicEncryption;
    public Boolean enableEncryptFieldHistory;
    public Boolean enableEncryptionSearchEnabled;
    public Boolean enableEventBusEncryption;
    public Boolean isMEKForEncryptionRequired;
    public Boolean isUseHighAssuranceKeysRequired;
    private String[] canEncryptManagedPackageFields_type_info = new String[]{'canEncryptManagedPackageFields','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDeterministicEncryption_type_info = new String[]{'enableDeterministicEncryption','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEncryptFieldHistory_type_info = new String[]{'enableEncryptFieldHistory','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEncryptionSearchEnabled_type_info = new String[]{'enableEncryptionSearchEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableEventBusEncryption_type_info = new String[]{'enableEventBusEncryption','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isMEKForEncryptionRequired_type_info = new String[]{'isMEKForEncryptionRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isUseHighAssuranceKeysRequired_type_info = new String[]{'isUseHighAssuranceKeysRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'canEncryptManagedPackageFields','enableDeterministicEncryption','enableEncryptFieldHistory','enableEncryptionSearchEnabled','enableEventBusEncryption','isMEKForEncryptionRequired','isUseHighAssuranceKeysRequired'};
}