public class PortalsSettings {
    public Boolean clickjackSSPLoginPage;
    public Boolean redirectPortalLoginToHttps;
    private String[] clickjackSSPLoginPage_type_info = new String[]{'clickjackSSPLoginPage','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] redirectPortalLoginToHttps_type_info = new String[]{'redirectPortalLoginToHttps','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'clickjackSSPLoginPage','redirectPortalLoginToHttps'};
}