public class PrivacySettings {
    public Boolean authorizationCaptureBrowser;
    public Boolean authorizationCaptureEmail;
    public Boolean authorizationCaptureIp;
    public Boolean authorizationCaptureLocation;
    public Boolean authorizationCustomSharing;
    public Boolean authorizationLockingAndVersioning;
    public Boolean enableConfigurableUserPIIActive;
    public Boolean enableConsentAuditTrail;
    public Boolean enableConsentEventStream;
    public Boolean enableDefaultMetadataValues;
    private String[] authorizationCaptureBrowser_type_info = new String[]{'authorizationCaptureBrowser','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] authorizationCaptureEmail_type_info = new String[]{'authorizationCaptureEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] authorizationCaptureIp_type_info = new String[]{'authorizationCaptureIp','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] authorizationCaptureLocation_type_info = new String[]{'authorizationCaptureLocation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] authorizationCustomSharing_type_info = new String[]{'authorizationCustomSharing','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] authorizationLockingAndVersioning_type_info = new String[]{'authorizationLockingAndVersioning','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableConfigurableUserPIIActive_type_info = new String[]{'enableConfigurableUserPIIActive','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableConsentAuditTrail_type_info = new String[]{'enableConsentAuditTrail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableConsentEventStream_type_info = new String[]{'enableConsentEventStream','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableDefaultMetadataValues_type_info = new String[]{'enableDefaultMetadataValues','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'authorizationCaptureBrowser','authorizationCaptureEmail','authorizationCaptureIp','authorizationCaptureLocation','authorizationCustomSharing','authorizationLockingAndVersioning','enableConfigurableUserPIIActive','enableConsentAuditTrail','enableConsentEventStream','enableDefaultMetadataValues'};
}