public class ProductSettings {
    public Boolean enableCascadeActivateToRelatedPrices;
    public Boolean enableMySettings;
    public Boolean enableQuantitySchedule;
    public Boolean enableRevenueSchedule;
    public Boolean enableSecureGuestUserRecordAccess;
    private String[] enableCascadeActivateToRelatedPrices_type_info = new String[]{'enableCascadeActivateToRelatedPrices','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableMySettings_type_info = new String[]{'enableMySettings','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableQuantitySchedule_type_info = new String[]{'enableQuantitySchedule','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableRevenueSchedule_type_info = new String[]{'enableRevenueSchedule','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSecureGuestUserRecordAccess_type_info = new String[]{'enableSecureGuestUserRecordAccess','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCascadeActivateToRelatedPrices','enableMySettings','enableQuantitySchedule','enableRevenueSchedule','enableSecureGuestUserRecordAccess'};
}