public class QuickTextSettings {
    public Boolean hideQuickTextUiInLtng;
    public Boolean lightningQuickTextEnabled;
    public Boolean quickTextsInFolders;
    private String[] hideQuickTextUiInLtng_type_info = new String[]{'hideQuickTextUiInLtng','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lightningQuickTextEnabled_type_info = new String[]{'lightningQuickTextEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] quickTextsInFolders_type_info = new String[]{'quickTextsInFolders','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'hideQuickTextUiInLtng','lightningQuickTextEnabled','quickTextsInFolders'};
}