public class RealTimeEvent {
    public String entityName;
    public Boolean isEnabled;
    private String[] entityName_type_info = new String[]{'entityName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isEnabled_type_info = new String[]{'isEnabled','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'entityName','isEnabled'};
}