public class RecordPageSettings {
    public Boolean enableActivityRelatedList;
    public Boolean enableFullRecordView;
    private String[] enableActivityRelatedList_type_info = new String[]{'enableActivityRelatedList','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableFullRecordView_type_info = new String[]{'enableFullRecordView','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableActivityRelatedList','enableFullRecordView'};
}