public class SalesWorkQueueSettings {
    public String featureName;
    public String targetEntity;
    public String targetField;
    private String[] featureName_type_info = new String[]{'featureName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] targetEntity_type_info = new String[]{'targetEntity','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] targetField_type_info = new String[]{'targetField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'featureName','targetEntity','targetField'};
}