public class SchemaSettings {
    public Boolean enableAdvancedCMTSecurity;
    public Boolean enableAdvancedCSSecurity;
    public Boolean enableListCustomSettingCreation;
    public Boolean enableSOSLOnCustomSettings;
    private String[] enableAdvancedCMTSecurity_type_info = new String[]{'enableAdvancedCMTSecurity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableAdvancedCSSecurity_type_info = new String[]{'enableAdvancedCSSecurity','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableListCustomSettingCreation_type_info = new String[]{'enableListCustomSettingCreation','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSOSLOnCustomSettings_type_info = new String[]{'enableSOSLOnCustomSettings','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableAdvancedCMTSecurity','enableAdvancedCSSecurity','enableListCustomSettingCreation','enableSOSLOnCustomSettings'};
}