public class SiteSettings {
    public String groupingStringEnum;
    public Boolean sorted;
    public StandardValue[] standardValue;
    private String[] groupingStringEnum_type_info = new String[]{'groupingStringEnum','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sorted_type_info = new String[]{'sorted','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] standardValue_type_info = new String[]{'standardValue','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'groupingStringEnum','sorted','standardValue'};
}