public class SurveySettings {
    public Boolean enableIndustriesCxmEnabled;
    public Boolean enableSurvey;
    public Boolean enableSurveyOwnerCanManageResponse;
    private String[] enableIndustriesCxmEnabled_type_info = new String[]{'enableIndustriesCxmEnabled','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSurvey_type_info = new String[]{'enableSurvey','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableSurveyOwnerCanManageResponse_type_info = new String[]{'enableSurveyOwnerCanManageResponse','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableIndustriesCxmEnabled','enableSurvey','enableSurveyOwnerCanManageResponse'};
}