public class SystemNotificationSettings {
    public Boolean disableDowntimeNotifications;
    public Boolean disableMaintenanceNotifications;
    private String[] disableDowntimeNotifications_type_info = new String[]{'disableDowntimeNotifications','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] disableMaintenanceNotifications_type_info = new String[]{'disableMaintenanceNotifications','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'disableDowntimeNotifications','disableMaintenanceNotifications'};
}