public class TopicsForObjects {
    public Boolean enableTopics;
    public String entityApiName;
    private String[] enableTopics_type_info = new String[]{'enableTopics','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] entityApiName_type_info = new String[]{'entityApiName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableTopics','entityApiName'};
}