public class WebToXSettings {
    public Boolean shouldHideRecordInfoInEmail;
    public Boolean webToCaseSpamFilter;
    public Boolean webToLeadSpamFilter;
    private String[] shouldHideRecordInfoInEmail_type_info = new String[]{'shouldHideRecordInfoInEmail','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] webToCaseSpamFilter_type_info = new String[]{'webToCaseSpamFilter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] webToLeadSpamFilter_type_info = new String[]{'webToLeadSpamFilter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'shouldHideRecordInfoInEmail','webToCaseSpamFilter','webToLeadSpamFilter'};
}