public class WebToCaseSettings {
    public String caseOrigin;
    public String defaultResponseTemplate;
    public Boolean enableWebToCase;
    private String[] caseOrigin_type_info = new String[]{'caseOrigin','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] defaultResponseTemplate_type_info = new String[]{'defaultResponseTemplate','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableWebToCase_type_info = new String[]{'enableWebToCase','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'caseOrigin','defaultResponseTemplate','enableWebToCase'};
}