public class AnalyticsCloudComponentLayoutItem {
    public String assetType;
    public String devName;
    public String error;
    public String filter;
    public Integer height;
    public Boolean hideOnError;
    public Boolean showHeader;
    public Boolean showSharing;
    public Boolean showTitle;
    public String width;
    private String[] assetType_type_info = new String[]{'assetType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] devName_type_info = new String[]{'devName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] error_type_info = new String[]{'error','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] filter_type_info = new String[]{'filter','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] height_type_info = new String[]{'height','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] hideOnError_type_info = new String[]{'hideOnError','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showHeader_type_info = new String[]{'showHeader','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showSharing_type_info = new String[]{'showSharing','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showTitle_type_info = new String[]{'showTitle','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] width_type_info = new String[]{'width','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assetType','devName','error','filter','height','hideOnError','showHeader','showSharing','showTitle','width'};
}