public class AnimationRule {
    public String animationFrequency;
    public String developerName;
    public Boolean isActive;
    public String masterLabel;
    public String recordTypeContext;
    public String recordTypeName;
    public String sobjectType;
    public String targetField;
    public String targetFieldChangeToValues;
    private String[] animationFrequency_type_info = new String[]{'animationFrequency','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] developerName_type_info = new String[]{'developerName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isActive_type_info = new String[]{'isActive','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] recordTypeContext_type_info = new String[]{'recordTypeContext','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] recordTypeName_type_info = new String[]{'recordTypeName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sobjectType_type_info = new String[]{'sobjectType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] targetField_type_info = new String[]{'targetField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] targetFieldChangeToValues_type_info = new String[]{'targetFieldChangeToValues','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'animationFrequency','developerName','isActive','masterLabel','recordTypeContext','recordTypeName','sobjectType','targetField','targetFieldChangeToValues'};
}