public class AppActionOverride {
    public String pageOrSobjectType;
    private String[] pageOrSobjectType_type_info = new String[]{'pageOrSobjectType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'pageOrSobjectType'};
}