public class AppBrand {
    public String footerColor;
    public String headerColor;
    public String logo;
    public Integer logoVersion;
    public Boolean shouldOverrideOrgTheme;
    private String[] footerColor_type_info = new String[]{'footerColor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] headerColor_type_info = new String[]{'headerColor','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] logo_type_info = new String[]{'logo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] logoVersion_type_info = new String[]{'logoVersion','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] shouldOverrideOrgTheme_type_info = new String[]{'shouldOverrideOrgTheme','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'footerColor','headerColor','logo','logoVersion','shouldOverrideOrgTheme'};
}