public class AppComponentList {
    public String alignment;
    public String[] components;
    private String[] alignment_type_info = new String[]{'alignment','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] components_type_info = new String[]{'components','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'alignment','components'};
}