public class AppPreferences {
    public Boolean enableCustomizeMyTabs;
    public Boolean enableKeyboardShortcuts;
    public Boolean enableListViewHover;
    public Boolean enableListViewReskin;
    public Boolean enableMultiMonitorComponents;
    public Boolean enablePinTabs;
    public Boolean enableTabHover;
    public Boolean enableTabLimits;
    public Boolean saveUserSessions;
    private String[] enableCustomizeMyTabs_type_info = new String[]{'enableCustomizeMyTabs','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableKeyboardShortcuts_type_info = new String[]{'enableKeyboardShortcuts','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableListViewHover_type_info = new String[]{'enableListViewHover','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableListViewReskin_type_info = new String[]{'enableListViewReskin','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableMultiMonitorComponents_type_info = new String[]{'enableMultiMonitorComponents','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enablePinTabs_type_info = new String[]{'enablePinTabs','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableTabHover_type_info = new String[]{'enableTabHover','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] enableTabLimits_type_info = new String[]{'enableTabLimits','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] saveUserSessions_type_info = new String[]{'saveUserSessions','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'enableCustomizeMyTabs','enableKeyboardShortcuts','enableListViewHover','enableListViewReskin','enableMultiMonitorComponents','enablePinTabs','enableTabHover','enableTabLimits','saveUserSessions'};
}