public class ComponentInstancePropertyListItem {
    public String value;
    public UiFormulaRule visibilityRule;
    private String[] value_type_info = new String[]{'value','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] visibilityRule_type_info = new String[]{'visibilityRule','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'value','visibilityRule'};
}