public class ComponentInstance {
    public ComponentInstanceProperty[] componentInstanceProperties;
    public String componentName;
    public String identifier;
    public UiFormulaRule visibilityRule;
    private String[] componentInstanceProperties_type_info = new String[]{'componentInstanceProperties','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] componentName_type_info = new String[]{'componentName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] identifier_type_info = new String[]{'identifier','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] visibilityRule_type_info = new String[]{'visibilityRule','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'componentInstanceProperties','componentName','identifier','visibilityRule'};
}