public class CustomNotificationType {
    public String customNotifTypeName;
    public String description;
    public Boolean desktop;
    public String masterLabel;
    public Boolean mobile;
    private String[] customNotifTypeName_type_info = new String[]{'customNotifTypeName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] desktop_type_info = new String[]{'desktop','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] mobile_type_info = new String[]{'mobile','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customNotifTypeName','description','desktop','masterLabel','mobile'};
}