public class CustomApplicationComponent {
    public String buttonIconUrl;
    public String buttonStyle;
    public String buttonText;
    public Integer buttonWidth;
    public Integer height;
    public Boolean isHeightFixed;
    public Boolean isHidden;
    public Boolean isWidthFixed;
    public String visualforcePage;
    public Integer width;
    private String[] buttonIconUrl_type_info = new String[]{'buttonIconUrl','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] buttonStyle_type_info = new String[]{'buttonStyle','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] buttonText_type_info = new String[]{'buttonText','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] buttonWidth_type_info = new String[]{'buttonWidth','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] height_type_info = new String[]{'height','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isHeightFixed_type_info = new String[]{'isHeightFixed','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isHidden_type_info = new String[]{'isHidden','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isWidthFixed_type_info = new String[]{'isWidthFixed','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] visualforcePage_type_info = new String[]{'visualforcePage','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] width_type_info = new String[]{'width','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'buttonIconUrl','buttonStyle','buttonText','buttonWidth','height','isHeightFixed','isHidden','isWidthFixed','visualforcePage','width'};
}