public class CustomHelpMenuItem {
    public String linkUrl;
    public String masterLabel;
    public Integer sortOrder;
    private String[] linkUrl_type_info = new String[]{'linkUrl','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sortOrder_type_info = new String[]{'sortOrder','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'linkUrl','masterLabel','sortOrder'};
}