public class FeedLayoutFilter {
    public String feedFilterName;
    public String feedFilterType;
    public String feedItemType;
    private String[] feedFilterName_type_info = new String[]{'feedFilterName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] feedFilterType_type_info = new String[]{'feedFilterType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] feedItemType_type_info = new String[]{'feedItemType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'feedFilterName','feedFilterType','feedItemType'};
}