public class FlexiPageEventTarget {
    public FlexiPageEventPropertyMapping[] mappings;
    public String method;
    public String name;
    public FlexiPageEventTargetProperty[] properties;
    public String type_x;
    private String[] mappings_type_info = new String[]{'mappings','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] method_type_info = new String[]{'method','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] properties_type_info = new String[]{'properties','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'mappings','method','name','properties','type_x'};
}