public class FlexiPageRegion {
    public String appendable;
    public ItemInstance[] itemInstances;
    public String mode;
    public String name;
    public String prependable;
    public String replaceable;
    public String type_x;
    private String[] appendable_type_info = new String[]{'appendable','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] itemInstances_type_info = new String[]{'itemInstances','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] mode_type_info = new String[]{'mode','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] name_type_info = new String[]{'name','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] prependable_type_info = new String[]{'prependable','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] replaceable_type_info = new String[]{'replaceable','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] type_x_type_info = new String[]{'type','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'appendable','itemInstances','mode','name','prependable','replaceable','type_x'};
}