public class FlexiPageEvent {
    public String sourceName;
    public FlexiPageEventSourceProperty[] sourceProperties;
    public String sourceType;
    public FlexiPageEventTarget[] targets;
    private String[] sourceName_type_info = new String[]{'sourceName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sourceProperties_type_info = new String[]{'sourceProperties','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] sourceType_type_info = new String[]{'sourceType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] targets_type_info = new String[]{'targets','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'sourceName','sourceProperties','sourceType','targets'};
}