public class HomePageLayout {
    public String[] narrowComponents;
    public String[] wideComponents;
    private String[] narrowComponents_type_info = new String[]{'narrowComponents','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] wideComponents_type_info = new String[]{'wideComponents','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'narrowComponents','wideComponents'};
}