public class HomePageComponent {
    public String body;
    public Integer height;
    public String[] links;
    public String page_x;
    public String pageComponentType;
    public Boolean showLabel;
    public Boolean showScrollbars;
    public String width;
    private String[] body_type_info = new String[]{'body','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] height_type_info = new String[]{'height','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] links_type_info = new String[]{'links','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] page_x_type_info = new String[]{'page','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] pageComponentType_type_info = new String[]{'pageComponentType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] showLabel_type_info = new String[]{'showLabel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] showScrollbars_type_info = new String[]{'showScrollbars','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] width_type_info = new String[]{'width','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'body','height','links','page_x','pageComponentType','showLabel','showScrollbars','width'};
}