public class ItemInstance {
    public ComponentInstance componentInstance;
    public FieldInstance fieldInstance;
    private String[] componentInstance_type_info = new String[]{'componentInstance','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] fieldInstance_type_info = new String[]{'fieldInstance','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'componentInstance','fieldInstance'};
}