public class KeyboardShortcuts {
    public CustomShortcut[] customShortcuts;
    public DefaultShortcut[] defaultShortcuts;
    private String[] customShortcuts_type_info = new String[]{'customShortcuts','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] defaultShortcuts_type_info = new String[]{'defaultShortcuts','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'customShortcuts','defaultShortcuts'};
}
