public class LightningExperienceTheme {
    public String defaultBrandingSet;
    public String description;
    public String masterLabel;
    public Boolean shouldOverrideLoadingImage;
    private String[] defaultBrandingSet_type_info = new String[]{'defaultBrandingSet','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] shouldOverrideLoadingImage_type_info = new String[]{'shouldOverrideLoadingImage','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'defaultBrandingSet','description','masterLabel','shouldOverrideLoadingImage'};
}