public class ListPlacement {
    public Integer height;
    public String location;
    public String units;
    public Integer width;
    private String[] height_type_info = new String[]{'height','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] location_type_info = new String[]{'location','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] units_type_info = new String[]{'units','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] width_type_info = new String[]{'width','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'height','location','units','width'};
}