public class PathAssistantStep {
    public String[] fieldNames;
    public String info;
    public String picklistValueName;
    private String[] fieldNames_type_info = new String[]{'fieldNames','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] info_type_info = new String[]{'info','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] picklistValueName_type_info = new String[]{'picklistValueName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'fieldNames','info','picklistValueName'};
}