public class QuickActionSendEmailOptions {
    public String defaultEmailTemplateName;
    public Boolean ignoreDefaultEmailTemplateSubject;
    private String[] defaultEmailTemplateName_type_info = new String[]{'defaultEmailTemplateName','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] ignoreDefaultEmailTemplateSubject_type_info = new String[]{'ignoreDefaultEmailTemplateSubject','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'defaultEmailTemplateName','ignoreDefaultEmailTemplateSubject'};
}