public class QuickActionLayoutItem {
    public Boolean emptySpace;
    public String field;
    public String uiBehavior;
    private String[] emptySpace_type_info = new String[]{'emptySpace','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] uiBehavior_type_info = new String[]{'uiBehavior','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'emptySpace','field','uiBehavior'};
}