public class QuickActionLayout {
    public String layoutSectionStyle;
    public QuickActionLayoutColumn[] quickActionLayoutColumns;
    private String[] layoutSectionStyle_type_info = new String[]{'layoutSectionStyle','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] quickActionLayoutColumns_type_info = new String[]{'quickActionLayoutColumns','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'layoutSectionStyle','quickActionLayoutColumns'};
}