public class ReportChartComponentLayoutItem {
    public Boolean cacheData;
    public String contextFilterableField;
    public String error;
    public Boolean hideOnError;
    public Boolean includeContext;
    public String reportName;
    public Boolean showTitle;
    public String size;
    private String[] cacheData_type_info = new String[]{'cacheData','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] contextFilterableField_type_info = new String[]{'contextFilterableField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] error_type_info = new String[]{'error','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] hideOnError_type_info = new String[]{'hideOnError','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] includeContext_type_info = new String[]{'includeContext','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] reportName_type_info = new String[]{'reportName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] showTitle_type_info = new String[]{'showTitle','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] size_type_info = new String[]{'size','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'cacheData','contextFilterableField','error','hideOnError','includeContext','reportName','showTitle','size'};
}