public class SidebarComponent {
    public String componentType;
    public String createAction;
    public Boolean enableLinking;
    public Integer height;
    public String label;
    public String lookup;
    public String page_x;
    public RelatedList[] relatedLists;
    public String unit;
    public String updateAction;
    public Integer width;
    private String[] componentType_type_info = new String[]{'componentType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] createAction_type_info = new String[]{'createAction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] enableLinking_type_info = new String[]{'enableLinking','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] height_type_info = new String[]{'height','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lookup_type_info = new String[]{'lookup','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] page_x_type_info = new String[]{'page','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] relatedLists_type_info = new String[]{'relatedLists','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] unit_type_info = new String[]{'unit','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] updateAction_type_info = new String[]{'updateAction','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] width_type_info = new String[]{'width','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'componentType','createAction','enableLinking','height','label','lookup','page_x','relatedLists','unit','updateAction','width'};
}