public class TabLimitConfig {
    public String maxNumberOfPrimaryTabs;
    public String maxNumberOfSubTabs;
    private String[] maxNumberOfPrimaryTabs_type_info = new String[]{'maxNumberOfPrimaryTabs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] maxNumberOfSubTabs_type_info = new String[]{'maxNumberOfSubTabs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'maxNumberOfPrimaryTabs','maxNumberOfSubTabs'};
}