public class AccountSharingRuleSettings {
    public String caseAccessLevel;
    public String contactAccessLevel;
    public String opportunityAccessLevel;
    private String[] caseAccessLevel_type_info = new String[]{'caseAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] contactAccessLevel_type_info = new String[]{'contactAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] opportunityAccessLevel_type_info = new String[]{'opportunityAccessLevel','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'caseAccessLevel','contactAccessLevel','opportunityAccessLevel'};
}