public class SharingRules {
    public SharingCriteriaRule[] sharingCriteriaRules;
    public SharingGuestRule[] sharingGuestRules;
    public SharingOwnerRule[] sharingOwnerRules;
    public SharingTerritoryRule[] sharingTerritoryRules;
    private String[] sharingCriteriaRules_type_info = new String[]{'sharingCriteriaRules','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] sharingGuestRules_type_info = new String[]{'sharingGuestRules','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] sharingOwnerRules_type_info = new String[]{'sharingOwnerRules','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] sharingTerritoryRules_type_info = new String[]{'sharingTerritoryRules','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'sharingCriteriaRules','sharingGuestRules','sharingOwnerRules','sharingTerritoryRules'};
}