public class FlowOutputFieldAssignment {
    public String assignToReference;
    public String field;
    private String[] assignToReference_type_info = new String[]{'assignToReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] field_type_info = new String[]{'field','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignToReference','field'};
}