public class FlowScreenRuleAction {
    public String attribute;
    public String fieldReference;
    public FlowElementReferenceOrValue value;
    private String[] attribute_type_info = new String[]{'attribute','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] fieldReference_type_info = new String[]{'fieldReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] value_type_info = new String[]{'value','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'attribute','fieldReference','value'};
}