public class FlowStageStepAssignee {
    public FlowElementReferenceOrValue assignee;
    public String assigneeType;
    private String[] assignee_type_info = new String[]{'assignee','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] assigneeType_type_info = new String[]{'assigneeType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignee','assigneeType'};
}