public class FlowInputValidationRule {
    public String errorMessage;
    public String formulaExpression;
    private String[] errorMessage_type_info = new String[]{'errorMessage','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] formulaExpression_type_info = new String[]{'formulaExpression','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'errorMessage','formulaExpression'};
}