public class FlowChoice {
    public String choiceText;
    public String dataType;
    public FlowChoiceUserInput userInput;
    public FlowElementReferenceOrValue value;
    private String[] choiceText_type_info = new String[]{'choiceText','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] dataType_type_info = new String[]{'dataType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] userInput_type_info = new String[]{'userInput','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] value_type_info = new String[]{'value','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'choiceText','dataType','userInput','value'};
}