public class FlowCondition {
    public String leftValueReference;
    public String operator;
    public FlowElementReferenceOrValue rightValue;
    private String[] leftValueReference_type_info = new String[]{'leftValueReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] operator_type_info = new String[]{'operator','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] rightValue_type_info = new String[]{'rightValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'leftValueReference','operator','rightValue'};
}