public class FlowRecordCreate {
    public String assignRecordIdToReference;
    public FlowConnector connector;
    public FlowConnector faultConnector;
    public FlowInputFieldAssignment[] inputAssignments;
    public String inputReference;
    public String object_x;
    public Boolean storeOutputAutomatically;
    private String[] assignRecordIdToReference_type_info = new String[]{'assignRecordIdToReference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] connector_type_info = new String[]{'connector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] faultConnector_type_info = new String[]{'faultConnector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] inputAssignments_type_info = new String[]{'inputAssignments','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] inputReference_type_info = new String[]{'inputReference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] object_x_type_info = new String[]{'object','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] storeOutputAutomatically_type_info = new String[]{'storeOutputAutomatically','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignRecordIdToReference','connector','faultConnector','inputAssignments','inputReference','object_x','storeOutputAutomatically'};
}