public class FlowCollectionSortOption {
    public Boolean doesPutEmptyStringAndNullFirst;
    public String sortField;
    public String sortOrder;
    private String[] doesPutEmptyStringAndNullFirst_type_info = new String[]{'doesPutEmptyStringAndNullFirst','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] sortField_type_info = new String[]{'sortField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortOrder_type_info = new String[]{'sortOrder','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'doesPutEmptyStringAndNullFirst','sortField','sortOrder'};
}