public class FlowElementReferenceOrValue {
    public String apexValue;
    public Boolean booleanValue;
    public DateTime dateTimeValue;
    public Date dateValue;
    public String elementReference;
    public Double numberValue;
    public String sobjectValue;
    public String stringValue;
    private String[] apexValue_type_info = new String[]{'apexValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] booleanValue_type_info = new String[]{'booleanValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] dateTimeValue_type_info = new String[]{'dateTimeValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dateValue_type_info = new String[]{'dateValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] elementReference_type_info = new String[]{'elementReference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] numberValue_type_info = new String[]{'numberValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] sobjectValue_type_info = new String[]{'sobjectValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] stringValue_type_info = new String[]{'stringValue','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apexValue','booleanValue','dateTimeValue','dateValue','elementReference','numberValue','sobjectValue','stringValue'};
}