public class FlowChoiceUserInput {
    public Boolean isRequired;
    public String promptText;
    public FlowInputValidationRule validationRule;
    private String[] isRequired_type_info = new String[]{'isRequired','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] promptText_type_info = new String[]{'promptText','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] validationRule_type_info = new String[]{'validationRule','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'isRequired','promptText','validationRule'};
}