public class FlowLoop {
    public String assignNextValueToReference;
    public String collectionReference;
    public String iterationOrder;
    public FlowConnector nextValueConnector;
    public FlowConnector noMoreValuesConnector;
    private String[] assignNextValueToReference_type_info = new String[]{'assignNextValueToReference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] collectionReference_type_info = new String[]{'collectionReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] iterationOrder_type_info = new String[]{'iterationOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] nextValueConnector_type_info = new String[]{'nextValueConnector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] noMoreValuesConnector_type_info = new String[]{'noMoreValuesConnector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignNextValueToReference','collectionReference','iterationOrder','nextValueConnector','noMoreValuesConnector'};
}