public class FlowTextTemplate {
    public Boolean isViewedAsPlainText;
    public String text;
    private String[] isViewedAsPlainText_type_info = new String[]{'isViewedAsPlainText','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] text_type_info = new String[]{'text','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'isViewedAsPlainText','text'};
}