public class FlowDynamicChoiceSet {
    public String dataType;
    public String displayField;
    public String filterLogic;
    public FlowRecordFilter[] filters;
    public Integer limit_x;
    public String object_x;
    public FlowOutputFieldAssignment[] outputAssignments;
    public String picklistField;
    public String picklistObject;
    public String sortField;
    public String sortOrder;
    public String valueField;
    private String[] dataType_type_info = new String[]{'dataType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] displayField_type_info = new String[]{'displayField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] filterLogic_type_info = new String[]{'filterLogic','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] filters_type_info = new String[]{'filters','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] limit_x_type_info = new String[]{'limit','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] object_x_type_info = new String[]{'object','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] outputAssignments_type_info = new String[]{'outputAssignments','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] picklistField_type_info = new String[]{'picklistField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] picklistObject_type_info = new String[]{'picklistObject','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortField_type_info = new String[]{'sortField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortOrder_type_info = new String[]{'sortOrder','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] valueField_type_info = new String[]{'valueField','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dataType','displayField','filterLogic','filters','limit_x','object_x','outputAssignments','picklistField','picklistObject','sortField','sortOrder','valueField'};
}