public class FlowAssignment {
    public FlowAssignmentItem[] assignmentItems;
    public FlowConnector connector;
    private String[] assignmentItems_type_info = new String[]{'assignmentItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] connector_type_info = new String[]{'connector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignmentItems','connector'};
}