public class FlowCollectionProcessor {
    public String assignNextValueToReference;
    public String collectionProcessorType;
    public String collectionReference;
    public FlowConnector connector;
    public Integer limit_x;
    public FlowCollectionMapItem[] mapItems;
    public String outputSObjectType;
    public FlowCollectionSortOption[] sortOptions;
    private String[] assignNextValueToReference_type_info = new String[]{'assignNextValueToReference','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] collectionProcessorType_type_info = new String[]{'collectionProcessorType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] collectionReference_type_info = new String[]{'collectionReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] connector_type_info = new String[]{'connector','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] limit_x_type_info = new String[]{'limit','http://soap.sforce.com/2006/04/metadata',null,'0','1','true'};
    private String[] mapItems_type_info = new String[]{'mapItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] outputSObjectType_type_info = new String[]{'outputSObjectType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] sortOptions_type_info = new String[]{'sortOptions','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'assignNextValueToReference','collectionProcessorType','collectionReference','connector','limit_x','mapItems','outputSObjectType','sortOptions'};
}