public class FlowNode {
    public String elementSubtype;
    public String label;
    public Integer locationX;
    public Integer locationY;
    private String[] elementSubtype_type_info = new String[]{'elementSubtype','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] label_type_info = new String[]{'label','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] locationX_type_info = new String[]{'locationX','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] locationY_type_info = new String[]{'locationY','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'elementSubtype','label','locationX','locationY'};
}