public class FlowConnector {
    public Boolean isGoTo;
    public String targetReference;
    private String[] isGoTo_type_info = new String[]{'isGoTo','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] targetReference_type_info = new String[]{'targetReference','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'isGoTo','targetReference'};
}