public class FlowFormula {
    public String dataType;
    public String expression;
    public Integer scale;
    private String[] dataType_type_info = new String[]{'dataType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] expression_type_info = new String[]{'expression','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] scale_type_info = new String[]{'scale','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'dataType','expression','scale'};
}