public class FlowVariable {
    public String apexClass;
    public String dataType;
    public Boolean isCollection;
    public Boolean isInput;
    public Boolean isOutput;
    public String objectType;
    public Integer scale;
    public FlowElementReferenceOrValue value;
    private String[] apexClass_type_info = new String[]{'apexClass','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] dataType_type_info = new String[]{'dataType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] isCollection_type_info = new String[]{'isCollection','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isInput_type_info = new String[]{'isInput','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isOutput_type_info = new String[]{'isOutput','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] objectType_type_info = new String[]{'objectType','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] scale_type_info = new String[]{'scale','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] value_type_info = new String[]{'value','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apexClass','dataType','isCollection','isInput','isOutput','objectType','scale','value'};
}