public class LightningBoltFeatures {
    public String description;
    public Integer order;
    public String title;
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] order_type_info = new String[]{'order','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] title_type_info = new String[]{'title','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'description','order','title'};
}