public class LightningBoltImages {
    public String image;
    public Integer order;
    private String[] image_type_info = new String[]{'image','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] order_type_info = new String[]{'order','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'image','order'};
}