public class ObjectMapping {
    public String inputObject;
    public ObjectMappingField[] mappingFields;
    public String outputObject;
    private String[] inputObject_type_info = new String[]{'inputObject','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] mappingFields_type_info = new String[]{'mappingFields','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] outputObject_type_info = new String[]{'outputObject','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'inputObject','mappingFields','outputObject'};
}