public class ObjectMappingField {
    public String inputField;
    public String outputField;
    private String[] inputField_type_info = new String[]{'inputField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] outputField_type_info = new String[]{'outputField','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'inputField','outputField'};
}