public class PackageVersion {
    public Integer majorNumber;
    public Integer minorNumber;
    public String namespace;
    private String[] majorNumber_type_info = new String[]{'majorNumber','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] minorNumber_type_info = new String[]{'minorNumber','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] namespace_type_info = new String[]{'namespace','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'majorNumber','minorNumber','namespace'};
}