public class DuplicateRuleFilter {
    public String booleanFilter;
    public DuplicateRuleFilterItem[] duplicateRuleFilterItems;
    private String[] booleanFilter_type_info = new String[]{'booleanFilter','http://soap.sforce.com/2006/04/metadata',null,'1','1','true'};
    private String[] duplicateRuleFilterItems_type_info = new String[]{'duplicateRuleFilterItems','http://soap.sforce.com/2006/04/metadata',null,'0','-1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'booleanFilter','duplicateRuleFilterItems'};
}