public class DuplicateRuleMatchRule {
    public String matchRuleSObjectType;
    public String matchingRule;
    public ObjectMapping objectMapping;
    private String[] matchRuleSObjectType_type_info = new String[]{'matchRuleSObjectType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] matchingRule_type_info = new String[]{'matchingRule','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] objectMapping_type_info = new String[]{'objectMapping','http://soap.sforce.com/2006/04/metadata',null,'1','1','true'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'matchRuleSObjectType','matchingRule','objectMapping'};
}