public class MatchingRuleItem {
    public String blankValueBehavior;
    public String fieldName;
    public String matchingMethod;
    private String[] blankValueBehavior_type_info = new String[]{'blankValueBehavior','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] fieldName_type_info = new String[]{'fieldName','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] matchingMethod_type_info = new String[]{'matchingMethod','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'blankValueBehavior','fieldName','matchingMethod'};
}
