public class AuraDefinition {
    public String defType;
    public String source;
    private String[] defType_type_info = new String[]{'defType','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] source_type_info = new String[]{'source','http://soap.sforce.com/2006/04/metadata',null,'1','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'defType','source'};
}