public class LightningComponentBundle {
    public Double apiVersion;
    public Capabilities capabilities;
    public String description;
    public Boolean isExplicitImport;
    public Boolean isExposed;
    public LwcResources lwcResources;
    public String masterLabel;
    public String runtimeNamespace;
    public String targetConfigs;
    public Targets targets;
    private String[] apiVersion_type_info = new String[]{'apiVersion','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] capabilities_type_info = new String[]{'capabilities','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] description_type_info = new String[]{'description','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isExplicitImport_type_info = new String[]{'isExplicitImport','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] isExposed_type_info = new String[]{'isExposed','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] lwcResources_type_info = new String[]{'lwcResources','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] masterLabel_type_info = new String[]{'masterLabel','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] runtimeNamespace_type_info = new String[]{'runtimeNamespace','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] targetConfigs_type_info = new String[]{'targetConfigs','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] targets_type_info = new String[]{'targets','http://soap.sforce.com/2006/04/metadata',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://soap.sforce.com/2006/04/metadata','true','false'};
    private String[] field_order_type_info = new String[]{'apiVersion','capabilities','description','isExplicitImport','isExposed','lwcResources','masterLabel','runtimeNamespace','targetConfigs','targets'};
}